import pytz


KR_EXCLUDE_DATES = ["2024-12-30", "2025-01-27"]
US_EXCLUDE_DATES = ["2025-01-09"]

KST = pytz.timezone("Asia/Seoul")
UTC = pytz.timezone("UTC")
USE = pytz.timezone("America/New_York")

NEED_TO_MULTIPLY_100 = ["vol", "vol_60", "momentum_1", "momentum_3", "momentum_6", "momentum_12", "current_ratio"]

DEFAULT_COLUMNS = ["Code", "Name", "country"]

NON_NUMERIC_COLUMNS = ["Code", "Name", "market", "sector", "country", "score"]

UNIT_MAP = {"percentage": "%", "times": "회", "score": "점", "multiple": "배", "ratio": ""}

MARKET_MAP = {
    "KOSPI": "코스피",
    "KOSDAQ": "코스닥",
    "NAS": "나스닥",
    "NYS": "뉴욕 증권 거래소",
    "AMS": "아멕스",
}

FACTOR_MAP = {
    "Code": "티커",
    "Name": "종목명",
    "country": "국가",
    "market": "시장",
    "sector": "산업",
    "score": "스코어",
    "abs_beta": "절대값 베타 (52주)",
    "abs_beta_60": "절대값 베타 (60일)",
    "beta": "베타 (52주)",
    "beta_60": "베타 (60일)",
    "close": "종가 (수정 전)",
    "disparity_10": "이격도 (10일)",
    "disparity_100": "이격도 (100일)",
    "disparity_20": "이격도 (20일)",
    "disparity_200": "이격도 (200일)",
    "disparity_5": "이격도 (5일)",
    "disparity_50": "이격도 (50일)",
    "marketCap": "시가총액",
    "median_trade": "중위 월간 거래량",
    "momentum_1": "모멘텀 (1개월)",
    "momentum_12": "모멘텀 (12개월)",
    "momentum_3": "모멘텀 (3개월)",
    "momentum_6": "모멘텀 (6개월)",
    "rsi_14": "RSI (14일)",
    "rsi_25": "RSI (25일)",
    "rsi_9": "RSI (9일)",
    "sharpe": "샤프 비율 (52주)",
    "sortino": "Sortino 비율 (52주)",
    "vol": "변동성 (52주)",
    "vol_60": "변동성 (60일)",
    "assetturnover": "Asset Turnover",
    "assetturnover_ttm": "Asset Turnover (TTM)",
    "borrow_rate": "차입 비율",
    "current_ratio": "유동 비율",
    "deptRatio": "부채 비율",
    "fscore": "F-score",
    "gpa": "GP/A",
    "gpa_ttm": "GP/A (TTM)",
    "gross_profit": "매출 총 이익",
    "gross_profit_ttm": "매출 총 이익 (TTM)",
    "operating_income": "영업 이익",
    "operating_income_ttm": "영업 이익 (TTM)",
    "reserve_ratio": "유보율",
    "rev": "매출액",
    "rev_ttm": "매출액 (TTM)",
    "roa": "ROA",
    "roa_ttm": "ROA (TTM)",
    "roe": "ROE",
    "roe_ttm": "ROE (TTM)",
    "z_score": "Altman Z-score",
    "pbr": "PBR",
    "pcr": "PCR",
    "pcr_ttm": "PCR (TTM)",
    "per": "PER",
    "per_ttm": "PER (TTM)",
    "pgpr": "PGPR",
    "pgpr_ttm": "PGPR (TTM)",
    "por": "POR",
    "por_ttm": "POR (TTM)",
    "psr": "PSR",
    "psr_ttm": "PSR (TTM)",
}

KR_TO_EN_MAP = {
    "티커": "Ticker",
    "종목명": "Name",
    "국가": "Country",
    "시장": "Market",
    "산업": "Sector",
    "스코어": "Score",
    "절대값 베타 (52주)": "Absolute Beta (52-week)",
    "절대값 베타 (60일)": "Absolute Beta (60-day)",
    "베타 (52주)": "Beta (52-week)",
    "베타 (60일)": "Beta (60-day)",
    "종가 (수정 전)": "Close Price (Pre-adjustment)",
    "이격도 (10일)": "Disparity (10-day)",
    "이격도 (100일)": "Disparity (100-day)",
    "이격도 (20일)": "Disparity (20-day)",
    "이격도 (200일)": "Disparity (200-day)",
    "이격도 (5일)": "Disparity (5-day)",
    "이격도 (50일)": "Disparity (50-day)",
    "시가총액": "Market Capitalization",
    "중위 월간 거래량": "Median Monthly Trading Volume",
    "모멘텀 (1개월)": "Momentum (1-month)",
    "모멘텀 (12개월)": "Momentum (12-month)",
    "모멘텀 (3개월)": "Momentum (3-month)",
    "모멘텀 (6개월)": "Momentum (6-month)",
    "RSI (14일)": "RSI (14-day)",
    "RSI (25일)": "RSI (25-day)",
    "RSI (9일)": "RSI (9-day)",
    "샤프 비율 (52주)": "Sharpe Ratio (52-week)",
    "Sortino 비율 (52주)": "Sortino Ratio (52-week)",
    "변동성 (52주)": "Volatility (52-week)",
    "변동성 (60일)": "Volatility (60-day)",
    "Asset Turnover": "Asset Turnover",
    "Asset Turnover (TTM)": "Asset Turnover (TTM)",
    "차입 비율": "Borrowing Ratio",
    "유동 비율": "Current Ratio",
    "부채 비율": "Debt Ratio",
    "F-score": "F-score",
    "GP/A": "GP/A",
    "GP/A (TTM)": "GP/A (TTM)",
    "매출 총 이익": "Gross Profit",
    "매출 총 이익 (TTM)": "Gross Profit (TTM)",
    "영업 이익": "Operating Income",
    "영업 이익 (TTM)": "Operating Income (TTM)",
    "유보율": "Reserve Ratio",
    "매출액": "Revenue",
    "매출액 (TTM)": "Revenue (TTM)",
    "ROA": "ROA",
    "ROA (TTM)": "ROA (TTM)",
    "ROE": "ROE",
    "ROE (TTM)": "ROE (TTM)",
    "Altman Z-score": "Altman Z-score",
    "PBR": "PBR",
    "PCR": "PCR",
    "PCR (TTM)": "PCR (TTM)",
    "PER": "PER",
    "PER (TTM)": "PER (TTM)",
    "PGPR": "PGPR",
    "PGPR (TTM)": "PGPR (TTM)",
    "POR": "POR",
    "POR (TTM)": "POR (TTM)",
    "PSR": "PSR",
    "PSR (TTM)": "PSR (TTM)",
}


REVERSE_FACTOR_MAP = {v: k for k, v in FACTOR_MAP.items()}
