import pytz


KR_EXCLUDE_DATES = ["2024-12-30", "2025-01-27"]
US_EXCLUDE_DATES = ["2025-01-09"]

KST = pytz.timezone("Asia/Seoul")
UTC = pytz.timezone("UTC")
USE = pytz.timezone("America/New_York")

NEED_TO_MULTIPLY_100 = ["vol", "vol_60", "momentum_1", "momentum_3", "momentum_6", "momentum_12", "current_ratio"]

NON_NUMERIC_COLUMNS = ["Code", "Name", "market", "sector", "country", "score", "Name_en", "sector_en"]

NON_NUMERIC_COLUMNS_ETF = [
    "Code",
    "country",
    "score",
    "ticker",
    "ctry",
    "kr_name",
    "en_name",
    "Name",
    "market",
    "listing_date",
    "base_index_name",
    "replication_method",
    "base_asset_classification",
    "manager",
    "tax_type",
    "is_hedge",
    "last_dividend_date",
    "manager",
    "tax_type",
    "is_hedge",
]

ETF_DEFAULT_SCREENER_COLUMNS = ["ticker", "market", "kr_name", "en_name"]

UNIT_MAP = {"percentage": "%", "times": "회", "score": "점", "multiple": "배", "ratio": ""}
UNIT_MAP_EN = {"percentage": "%", "times": "", "score": "", "multiple": "", "ratio": ""}

MARKET_MAP = {
    "KOSPI": "코스피",
    "KOSDAQ": "코스닥",
    "NAS": "나스닥",
    "NYS": "뉴욕 증권 거래소",
    "AMS": "아멕스",
    "BATS": "바츠",
}

MARKET_KOREAN_TO_ENGLISH_MAP = {
    "코스피": "KOSPI",
    "코스닥": "KOSDAQ",
    "나스닥": "NASDAQ",
    "뉴욕 증권 거래소": "NYSE",
    "아멕스": "AMS",
    "바츠": "BATS",
}

FACTOR_MAP = {
    "Code": "티커",
    "ticker": "티 커",  # 띄어쓰기 제거시 에러 발생함
    "Name": "종목명",
    "kr_name": "종목명(한)",
    "en_name": "종목명(영)",
    "country": "국가",
    "market": "시장",
    "sector": "산업",
    "score": "스코어",
    "abs_beta": "절대값 베타 (52주)",
    "abs_beta_60": "절대값 베타 (60일)",
    "beta": "베타 (52주)",
    "beta_60": "베타 (60일)",
    "close": "종가 (수정 전)",
    "disparity_10": "이격도 (10일)",
    "disparity_100": "이격도 (100일)",
    "disparity_20": "이격도 (20일)",
    "disparity_200": "이격도 (200일)",
    "disparity_5": "이격도 (5일)",
    "disparity_50": "이격도 (50일)",
    "marketCap": "시가총액",
    "median_trade": "중위 월간 거래량",
    "momentum_1": "모멘텀 (1개월)",
    "momentum_12": "모멘텀 (12개월)",
    "momentum_3": "모멘텀 (3개월)",
    "momentum_6": "모멘텀 (6개월)",
    "rsi_14": "RSI (14일)",
    "rsi_25": "RSI (25일)",
    "rsi_9": "RSI (9일)",
    "sharpe": "샤프 비율 (52주)",
    "sortino": "Sortino 비율 (52주)",
    "vol": "변동성 (52주)",
    "vol_60": "변동성 (60일)",
    "assetturnover": "Asset Turnover",
    "assetturnover_ttm": "Asset Turnover (TTM)",
    "borrow_rate": "차입 비율",
    "current_ratio": "유동 비율",
    "deptRatio": "부채 비율",
    "fscore": "F-score",
    "gpa": "GP/A",
    "gpa_ttm": "GP/A (TTM)",
    "gross_profit": "매출 총 이익",
    "gross_profit_ttm": "매출 총 이익 (TTM)",
    "operating_income": "영업 이익",
    "operating_income_ttm": "영업 이익 (TTM)",
    "reserve_ratio": "유보율",
    "rev": "매출액",
    "rev_ttm": "매출액 (TTM)",
    "roa": "ROA",
    "roa_ttm": "ROA (TTM)",
    "roe": "ROE",
    "roe_ttm": "ROE (TTM)",
    "z_score": "Altman Z-score",
    "pbr": "PBR",
    "pcr": "PCR",
    "pcr_ttm": "PCR (TTM)",
    "per": "PER",
    "per_ttm": "PER (TTM)",
    "pgpr": "PGPR",
    "pgpr_ttm": "PGPR (TTM)",
    "por": "POR",
    "por_ttm": "POR (TTM)",
    "psr": "PSR",
    "psr_ttm": "PSR (TTM)",
    ########################################################
    # ETF
    ########################################################
    "dividend_count": "5년 연평균 배당 횟수",
    "last_dividend_per_share": "최근 주당 배당금",
    "recent_dividend_yield": "직전 년도 배당 수익률",
    "dividend_growth_rate_3y": "배당 성장률 (3년)",
    "dividend_growth_rate_5y": "배당 성장률 (5년)",
    "total_fee": "총 수수료",
    "ba_absolute_spread": "Bid-Ask 절대 스프레드",
    "ba_relative_spread": "Bid-Ask 상대 스프레드",
    "ba_spread_20d_avg": "20일 평균 Bid-Ask 스프레드",
    "ba_spread_20d_std": "20일 표준 편차 Bid-Ask 스프레드",
    "ba_spread_1d_change": "1일 변화 Bid-Ask 스프레드",
    "ba_spread_20d_change": "20일 변화 Bid-Ask 스프레드",
    "listing_date": "상장일",
    "base_index_name": "기준 지수",
    "replication_method": "복제 방법",
    "base_asset_classification": "기본 자산 분류",
    "manager": "운용사",
    "tax_type": "세금 유형",
    "is_hedge": "헤지 여부",
    "last_dividend_date": "최근 배당일",
    "risk_rating": "위험 등급",
    "ctry": "국 가",  # 띄어쓰기 제거시 에러 발생함
}

FACTOR_MAP_EN = {
    "Code": "Ticker",
    "Name_en": "Name",
    "country": "Country",
    "market": "Market",
    "sector_en": "Sector",
    "score": "Score",
    "abs_beta": "Absolute Beta (52-week)",
    "abs_beta_60": "Absolute Beta (60-day)",
    "beta": "Beta (52-week)",
    "beta_60": "Beta (60-day)",
    "close": "Close Price (Pre-adjustment)",
    "disparity_10": "Disparity (10-day)",
    "disparity_100": "Disparity (100-day)",
    "disparity_20": "Disparity (20-day)",
    "disparity_200": "Disparity (200-day)",
    "disparity_5": "Disparity (5-day)",
    "disparity_50": "Disparity (50-day)",
    "marketCap": "Market Capitalization",
    "median_trade": "Median Monthly Trading Volume",
    "momentum_1": "Momentum (1-month)",
    "momentum_12": "Momentum (12-month)",
    "momentum_3": "Momentum (3-month)",
    "momentum_6": "Momentum (6-month)",
    "rsi_14": "RSI (14-day)",
    "rsi_25": "RSI (25-day)",
    "rsi_9": "RSI (9-day)",
    "sharpe": "Sharpe Ratio (52-week)",
    "sortino": "Sortino Ratio (52-week)",
    "vol": "Volatility (52-week)",
    "vol_60": "Volatility (60-day)",
    "assetturnover": "Asset Turnover",
    "assetturnover_ttm": "Asset Turnover (TTM)",
    "borrow_rate": "Borrowing Ratio",
    "current_ratio": "Current Ratio",
    "deptRatio": "Debt Ratio",
    "fscore": "F-score",
    "gpa": "GP/A",
    "gpa_ttm": "GP/A (TTM)",
    "gross_profit": "Gross Profit",
    "gross_profit_ttm": "Gross Profit (TTM)",
    "operating_income": "Operating Income",
    "operating_income_ttm": "Operating Income (TTM)",
    "reserve_ratio": "Reserve Ratio",
    "rev": "Revenue",
    "rev_ttm": "Revenue (TTM)",
    "roa": "ROA",
    "roa_ttm": "ROA (TTM)",
    "roe": "ROE",
    "roe_ttm": "ROE (TTM)",
    "z_score": "Altman Z-score",
    "pbr": "PBR",
    "pcr": "PCR",
    "pcr_ttm": "PCR (TTM)",
    "per": "PER",
    "per_ttm": "PER (TTM)",
    "pgpr": "PGPR",
    "pgpr_ttm": "PGPR (TTM)",
    "por": "POR",
    "por_ttm": "POR (TTM)",
    "psr": "PSR",
    "psr_ttm": "PSR (TTM)",
    ########################################################
    # ETF
    ########################################################
    "dividend_count": "5Y avg dividend frequency",
    "last_dividend_per_share": "Last dividend per share",
    "recent_dividend_yield": "Last annual dividend yield",
    "dividend_growth_rate_3y": "Dividend growth (3Y)",
    "dividend_growth_rate_5y": "Dividend growth (5Y)",
    "total_fee": "Total fee",
    "ba_absolute_spread": "Bid-Ask absolute spread",
    "ba_relative_spread": "Bid-Ask relative spread",
    "ba_spread_20d_avg": "20D avg Bid-Ask spread",
    "ba_spread_20d_std": "20D std dev Bid-Ask spread",
    "ba_spread_1d_change": "1D change Bid-Ask spread",
    "ba_spread_20d_change": "20D change Bid-Ask spread",
}

FACTOR_KOREAN_TO_ENGLISH_MAP = {
    "티커": "Ticker",
    "종목명": "Name",
    "국가": "Country",
    "시장": "Market",
    "산업": "Sector",
    "스코어": "Score",
    "절대값 베타 (52주)": "Absolute Beta (52-week)",
    "절대값 베타 (60일)": "Absolute Beta (60-day)",
    "베타 (52주)": "Beta (52-week)",
    "베타 (60일)": "Beta (60-day)",
    "종가 (수정 전)": "Close Price (Pre-adjustment)",
    "이격도 (10일)": "Disparity (10-day)",
    "이격도 (100일)": "Disparity (100-day)",
    "이격도 (20일)": "Disparity (20-day)",
    "이격도 (200일)": "Disparity (200-day)",
    "이격도 (5일)": "Disparity (5-day)",
    "이격도 (50일)": "Disparity (50-day)",
    "시가총액": "Market Capitalization",
    "중위 월간 거래량": "Median Monthly Trading Volume",
    "모멘텀 (1개월)": "Momentum (1-month)",
    "모멘텀 (12개월)": "Momentum (12-month)",
    "모멘텀 (3개월)": "Momentum (3-month)",
    "모멘텀 (6개월)": "Momentum (6-month)",
    "RSI (14일)": "RSI (14-day)",
    "RSI (25일)": "RSI (25-day)",
    "RSI (9일)": "RSI (9-day)",
    "샤프 비율 (52주)": "Sharpe Ratio (52-week)",
    "Sortino 비율 (52주)": "Sortino Ratio (52-week)",
    "변동성 (52주)": "Volatility (52-week)",
    "변동성 (60일)": "Volatility (60-day)",
    "Asset Turnover": "Asset Turnover",
    "Asset Turnover (TTM)": "Asset Turnover (TTM)",
    "차입 비율": "Borrowing Ratio",
    "유동 비율": "Current Ratio",
    "부채 비율": "Debt Ratio",
    "F-score": "F-score",
    "GP/A": "GP/A",
    "GP/A (TTM)": "GP/A (TTM)",
    "매출 총 이익": "Gross Profit",
    "매출 총 이익 (TTM)": "Gross Profit (TTM)",
    "영업 이익": "Operating Income",
    "영업 이익 (TTM)": "Operating Income (TTM)",
    "유보율": "Reserve Ratio",
    "매출액": "Revenue",
    "매출액 (TTM)": "Revenue (TTM)",
    "ROA": "ROA",
    "ROA (TTM)": "ROA (TTM)",
    "ROE": "ROE",
    "ROE (TTM)": "ROE (TTM)",
    "Altman Z-score": "Altman Z-score",
    "PBR": "PBR",
    "PCR": "PCR",
    "PCR (TTM)": "PCR (TTM)",
    "PER": "PER",
    "PER (TTM)": "PER (TTM)",
    "PGPR": "PGPR",
    "PGPR (TTM)": "PGPR (TTM)",
    "POR": "POR",
    "POR (TTM)": "POR (TTM)",
    "PSR": "PSR",
    "PSR (TTM)": "PSR (TTM)",
}

REVERSE_FACTOR_MAP = {v: k for k, v in FACTOR_MAP.items()}
REVERSE_FACTOR_MAP_EN = {v: k for k, v in FACTOR_MAP_EN.items()}

########################################################
# ETF
########################################################

ETF_DATA_DIR = "check_data/etf"
KRX_DIR = "check_data/etf_krx"
PARQUET_DIR = "parquet"
MORNINGSTAR_DIR = "check_data/etf_morningstar"

ETF_FACTOR_LIST = [
    "ticker",
    "Code",
    "date",
    "open",
    "high",
    "low",
    "close",
    "volume",
    "bid",
    "ask",
    "num_shrs",
    "trade_amount",
    "market_cap",
    "momentum_1",
    "momentum_3",
    "momentum_6",
    "momentum_12",
    "ba_absolute_spread",
    "ba_relative_spread",
    "ba_spread_20d_avg",
    "ba_spread_20d_std",
    "ba_spread_1d_change",
    "ba_spread_20d_change",
    "disparity_5",
    "disparity_10",
    "disparity_20",
    "disparity_50",
    "disparity_100",
    "disparity_200",
    "vol_60",
    "vol",
    "rsi_9",
    "rsi_14",
    "rsi_25",
    "sharpe",
    "sortino",
    "return_1m",
    "return_3m",
    "return_6m",
    "return_1y",
    "week_52_high",
    "week_52_low",
    "drawdown_1y",
    "median_trade",
    "dividend_count",
    "last_dividend_date",
    "last_dividend_per_share",
    "recent_dividend_yield",
    "dividend_growth_rate_3y",
    "dividend_growth_rate_5y",
    "ctry",
    "market",
    "kr_name",
    "en_name",
    "Name",
    "listing_date",
    "base_index_name",
    "tracking_multiplier",
    "replication_method",
    "base_asset_classification",
    "manager",
    "total_fee",
    "tax_type",
    "tracking_error",
    "disparity",
    "volatility",
    "is_hedge",
]
FACTOR_MAP_ETF = {v: k for k, v in FACTOR_MAP.items() if k in ETF_FACTOR_LIST}
