services:
    celery_worker:
        build:
            context: .
            dockerfile: Dockerfile.batch
        command: python -m app.celery_worker
        mem_limit: 3g
        memswap_limit: 3g
        restart: unless-stopped
        env_file:
            - .env.${ENV:-dev}
        environment:
            - IN_DOCKER=true
            - ENV=${ENV:-dev}
        depends_on:
            - rabbitmq
            - redis
        volumes:
            - .:/app
        ports:
            - "8000:8000"

    rabbitmq:
        image: rabbitmq:3.11.1-management
        expose:
            - 5672
            - 15672
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin

    redis:
        image: redis:6.0.6
        expose:
            - 6379

    pushgateway:
        image: prom/pushgateway:latest
        ports:
        - "9091:9091"
        restart: unless-stopped
