groups:
- name: prometheus_alerts
  rules:
  - alert: PrometheusHighMemoryUsage
    expr: (process_resident_memory_bytes{job="prometheus"} / 1073741824) > 0.8
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Prometheus high memory usage ({{ $value | printf \"%.2f\" }}GB)"
      description: "Prometheus memory usage is above 80% of its limit."

  - alert: PrometheusTSDBCompactionErrors
    expr: increase(prometheus_tsdb_compactions_failed_total[1h]) > 0
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: "Prometheus TSDB compaction errors"
      description: "Prometheus has encountered {{ $value }} compaction errors in the last hour."
