"""v17

Revision ID: 00f4295ba651
Revises: f6044e0e242d
Create Date: 2025-04-21 16:14:41.636339

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00f4295ba651"
down_revision: Union[str, None] = "f6044e0e242d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_message", sa.Column("root_message_id", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_chat_message_root_message_id"), "chat_message", ["root_message_id"], unique=False)
    op.create_foreign_key(None, "chat_message", "chat_message", ["root_message_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat_message", type_="foreignkey")
    op.drop_index(op.f("ix_chat_message_root_message_id"), table_name="chat_message")
    op.drop_column("chat_message", "root_message_id")
    # ### end Alembic commands ###
