"""v11

Revision ID: 11018e08ad07
Revises: 98f45bac4643
Create Date: 2025-03-27 22:05:54.526035

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "11018e08ad07"
down_revision: Union[str, None] = "98f45bac4643"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_using_history", sa.Column("refund_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_using_history", "refund_at")
    # ### end Alembic commands ###
