"""empty message

Revision ID: 19d4b9ffd5df
Revises: 9c4fc37d4490
Create Date: 2025-04-30 15:25:30.915033

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19d4b9ffd5df"
down_revision: Union[str, None] = "9c4fc37d4490"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_feedback",
        sa.Column("response_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("is_liked", sa.Boolean(), nullable=False),
        sa.Column("feedback", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["response_id"], ["chat_message.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["alphafinder_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("response_id"),
    )
    op.create_index(op.f("ix_chat_feedback_response_id"), "chat_feedback", ["response_id"], unique=False)
    op.create_index(op.f("ix_chat_feedback_user_id"), "chat_feedback", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_feedback_user_id"), table_name="chat_feedback")
    op.drop_index(op.f("ix_chat_feedback_response_id"), table_name="chat_feedback")
    op.drop_table("chat_feedback")
    # ### end Alembic commands ###
