"""empty message

Revision ID: 23f87d496452
Revises: 241f4218b01e
Create Date: 2025-04-14 20:53:30.703741

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23f87d496452"
down_revision: Union[str, None] = "241f4218b01e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alphafinder_user",
        "subscription_level",
        existing_type=mysql.INTEGER(),
        server_default=None,
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alphafinder_user",
        "subscription_level",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'1'"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
