"""empty message

Revision ID: 3003aa1a8c8f
Revises: fec903e65fb6
Create Date: 2025-03-14 10:34:08.426242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "3003aa1a8c8f"
down_revision: Union[str, None] = "fec903e65fb6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "screener_groups",
        "user_id",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.create_foreign_key(None, "screener_groups", "alphafinder_user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "screener_groups", type_="foreignkey")
    op.alter_column(
        "screener_groups",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
