"""v18

Revision ID: 32368389d589
Revises: 00f4295ba651
Create Date: 2025-04-21 18:16:18.052420

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32368389d589"
down_revision: Union[str, None] = "00f4295ba651"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("bookmarks_ibfk_2", "bookmarks", type_="foreignkey")
    op.drop_constraint("comment_likes_ibfk_2", "comment_likes", type_="foreignkey")
    op.drop_constraint("comments_ibfk_3", "comments", type_="foreignkey")
    op.drop_constraint("post_likes_ibfk_2", "post_likes", type_="foreignkey")
    op.drop_constraint("posts_ibfk_2", "posts", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("posts_ibfk_2", "posts", "alphafinder_user", ["user_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key("post_likes_ibfk_2", "post_likes", "alphafinder_user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key("comments_ibfk_3", "comments", "alphafinder_user", ["user_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(
        "comment_likes_ibfk_2", "comment_likes", "alphafinder_user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key("bookmarks_ibfk_2", "bookmarks", "alphafinder_user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###
