"""empty message

Revision ID: 33001328a26b
Revises:
Create Date: 2025-02-20 15:08:26.423311

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "33001328a26b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alphafinder_oauth_token",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("access_token_hash", sa.String(length=64), nullable=False),
        sa.Column("refresh_token", sa.String(length=1000), nullable=False),
        sa.Column("access_token", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alphafinder_oauth_token_access_token_hash"),
        "alphafinder_oauth_token",
        ["access_token_hash"],
        unique=False,
    )
    op.create_table(
        "alphafinder_user",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("nickname", sa.String(length=100), nullable=False),
        sa.Column("profile_image", mysql.LONGTEXT(), nullable=True),
        sa.Column("image_format", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nickname"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stock_statistics",
        sa.Column("stock_ticker", sa.String(length=20), nullable=False),
        sa.Column("daily_post_count", sa.Integer(), nullable=True),
        sa.Column("last_tagged_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("stock_ticker"),
    )
    op.create_index(
        "idx_stock_statistics_daily_posts", "stock_statistics", [sa.text("daily_post_count DESC")], unique=False
    )
    op.create_index("idx_stock_statistics_last_tagged", "stock_statistics", ["last_tagged_at"], unique=False)
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("image_url", mysql.LONGTEXT(), nullable=True),
        sa.Column("image_format", sa.String(length=20), nullable=True),
        sa.Column("like_count", sa.Integer(), nullable=True),
        sa.Column("comment_count", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["alphafinder_user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_posts_category_id", "posts", ["category_id"], unique=False)
    op.create_index("idx_posts_created_at", "posts", ["created_at"], unique=False)
    op.create_index("idx_posts_like_count", "posts", ["like_count"], unique=False)
    op.create_index("idx_posts_user_id", "posts", ["user_id"], unique=False)
    op.create_table(
        "user_stock_interest",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["alphafinder_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_stock_interest_user_id"), "user_stock_interest", ["user_id"], unique=False)
    op.create_table(
        "bookmarks",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["alphafinder_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("post_id", "user_id"),
    )
    op.create_index("idx_bookmarks_user", "bookmarks", ["user_id"], unique=False)
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=True, comment="댓글 깊이"),
        sa.Column("parent_id", sa.Integer(), nullable=True, comment="부모 댓글 ID"),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["comments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["alphafinder_user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_comments_depth_parent", "comments", ["depth", "parent_id"], unique=False)
    op.create_index("idx_comments_parent_id", "comments", ["parent_id"], unique=False)
    op.create_index("idx_comments_post_id", "comments", ["post_id"], unique=False)
    op.create_index("idx_comments_user_id", "comments", ["user_id"], unique=False)
    op.create_table(
        "post_likes",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("is_liked", sa.Boolean(), nullable=True, comment="좋아요/싫어요 여부"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["alphafinder_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("post_id", "user_id"),
    )
    op.create_index("idx_post_likes_user", "post_likes", ["user_id"], unique=False)
    op.create_table(
        "post_statistics",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("daily_likes_count", sa.Integer(), nullable=True),
        sa.Column("last_liked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("post_id"),
    )
    op.create_index(
        "idx_post_statistics_daily_likes", "post_statistics", [sa.text("daily_likes_count DESC")], unique=False
    )
    op.create_index("idx_post_statistics_last_liked", "post_statistics", ["last_liked_at"], unique=False)
    op.create_table(
        "post_stocks",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("stock_ticker", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("post_id", "stock_ticker"),
    )
    op.create_index("idx_post_stocks_stock_ticker", "post_stocks", ["stock_ticker"], unique=False)
    op.create_table(
        "comment_likes",
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("is_liked", sa.Boolean(), nullable=True, comment="좋아요/싫어요 여부"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["comment_id"], ["comments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["alphafinder_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("comment_id", "user_id"),
    )
    op.create_index("idx_comment_likes_user", "comment_likes", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_comment_likes_user", table_name="comment_likes")
    op.drop_table("comment_likes")
    op.drop_index("idx_post_stocks_stock_ticker", table_name="post_stocks")
    op.drop_table("post_stocks")
    op.drop_index("idx_post_statistics_last_liked", table_name="post_statistics")
    op.drop_index("idx_post_statistics_daily_likes", table_name="post_statistics")
    op.drop_table("post_statistics")
    op.drop_index("idx_post_likes_user", table_name="post_likes")
    op.drop_table("post_likes")
    op.drop_index("idx_comments_user_id", table_name="comments")
    op.drop_index("idx_comments_post_id", table_name="comments")
    op.drop_index("idx_comments_parent_id", table_name="comments")
    op.drop_index("idx_comments_depth_parent", table_name="comments")
    op.drop_table("comments")
    op.drop_index("idx_bookmarks_user", table_name="bookmarks")
    op.drop_table("bookmarks")
    op.drop_index(op.f("ix_user_stock_interest_user_id"), table_name="user_stock_interest")
    op.drop_table("user_stock_interest")
    op.drop_index("idx_posts_user_id", table_name="posts")
    op.drop_index("idx_posts_like_count", table_name="posts")
    op.drop_index("idx_posts_created_at", table_name="posts")
    op.drop_index("idx_posts_category_id", table_name="posts")
    op.drop_table("posts")
    op.drop_index("idx_stock_statistics_last_tagged", table_name="stock_statistics")
    op.drop_index("idx_stock_statistics_daily_posts", table_name="stock_statistics")
    op.drop_table("stock_statistics")
    op.drop_table("categories")
    op.drop_table("alphafinder_user")
    op.drop_index(op.f("ix_alphafinder_oauth_token_access_token_hash"), table_name="alphafinder_oauth_token")
    op.drop_table("alphafinder_oauth_token")
    # ### end Alembic commands ###
