"""empty message

Revision ID: 40a22208847a
Revises: 4981285b8887
Create Date: 2025-04-03 14:27:31.530284

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40a22208847a"
down_revision: Union[str, None] = "4981285b8887"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alphafinder_user",
        "subscription_level",
        existing_type=mysql.INTEGER(),
        server_default=None,
        existing_nullable=True,
    )
    op.add_column(
        "screener_stock_filters",
        sa.Column("type", sa.Enum("SLIDER", "MULTI", "SINGLE", name="factortypeenum"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("screener_stock_filters", "type")
    op.alter_column(
        "alphafinder_user",
        "subscription_level",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'1'"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
