"""v20

Revision ID: 44c701c54ee9
Revises: e7d97c56bbac
Create Date: 2025-04-22 16:11:16.078842

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44c701c54ee9"
down_revision: Union[str, None] = "e7d97c56bbac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alphafinder_interest_group",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_editable", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uix_user_id_name"),
    )
    op.create_index("idx_user_id_order", "alphafinder_interest_group", ["user_id", "order"], unique=False)

    op.create_table(
        "alphafinder_interest_stock",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=True),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["alphafinder_interest_group.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "ticker", name="uix_group_id_ticker"),
    )
    op.create_index(
        op.f("ix_alphafinder_interest_stock_group_id"), "alphafinder_interest_stock", ["group_id"], unique=False
    )
    op.create_index("idx_group_id_order", "alphafinder_interest_stock", ["group_id", "order"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_group_id_order", table_name="alphafinder_interest_stock")
    op.drop_index(op.f("ix_alphafinder_interest_stock_group_id"), table_name="alphafinder_interest_stock")
    op.drop_table("alphafinder_interest_stock")
    op.drop_index("idx_user_id_order", table_name="alphafinder_interest_group")
    op.drop_table("alphafinder_interest_group")
    # ### end Alembic commands ###
