"""empty message

Revision ID: 4981285b8887
Revises: 11018e08ad07
Create Date: 2025-04-02 15:50:39.146594

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "4981285b8887"
down_revision: Union[str, None] = "11018e08ad07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alphafinder_user",
        "subscription_level",
        existing_type=mysql.INTEGER(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "screener_factor_filters",
        "category",
        existing_type=mysql.ENUM("technical", "fundamental", "valuation", "dividend", "growth", "custom"),
        nullable=False,
    )
    op.alter_column(
        "screener_sort_infos",
        "category",
        existing_type=mysql.ENUM("technical", "fundamental", "valuation", "dividend", "growth", "custom"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "screener_sort_infos",
        "category",
        existing_type=mysql.ENUM("technical", "fundamental", "valuation", "dividend", "growth", "custom"),
        nullable=True,
    )
    op.alter_column(
        "screener_factor_filters",
        "category",
        existing_type=mysql.ENUM("technical", "fundamental", "valuation", "dividend", "growth", "custom"),
        nullable=True,
    )
    op.alter_column(
        "alphafinder_user",
        "subscription_level",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'1'"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
