"""empty message

Revision ID: 5c99928adff0
Revises: 779c1e837862
Create Date: 2025-03-20 09:51:46.341554

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c99928adff0"
down_revision: Union[str, None] = "779c1e837862"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "alphafinder_user", ["email"])
    op.add_column("toss_payment_history", sa.Column("email", sa.String(length=100), nullable=False))
    op.add_column("toss_payment_history", sa.Column("payment_method", sa.String(length=100), nullable=True))
    op.drop_constraint("toss_payment_history_ibfk_1", "toss_payment_history", type_="foreignkey")
    op.create_foreign_key(None, "toss_payment_history", "alphafinder_user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "toss_payment_history", type_="foreignkey")
    op.create_foreign_key(
        "toss_payment_history_ibfk_1", "toss_payment_history", "alphafinder_user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("toss_payment_history", "payment_method")
    op.drop_column("toss_payment_history", "email")
    op.drop_constraint(None, "alphafinder_user", type_="unique")
    # ### end Alembic commands ###
