"""v7

Revision ID: 80266bf3a203
Revises: dd55757ebda2
Create Date: 2025-03-26 18:50:22.587504

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "80266bf3a203"
down_revision: Union[str, None] = "dd55757ebda2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alphafinder_coupon_box", sa.Column("coupon_status", sa.String(length=10), nullable=False, comment="쿠폰 상태")
    )
    op.add_column("alphafinder_user", sa.Column("subscription_name", sa.String(length=100), nullable=True))
    op.drop_constraint("toss_receipt_ibfk_1", "toss_receipt", type_="foreignkey")
    op.drop_column("toss_receipt", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("toss_receipt", sa.Column("user_id", mysql.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        "toss_receipt_ibfk_1", "toss_receipt", "alphafinder_user", ["user_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("alphafinder_user", "subscription_name")
    op.drop_column("alphafinder_coupon_box", "coupon_status")
    # ### end Alembic commands ###
