"""empty message

Revision ID: 89b358b81f13
Revises: 8cf0fe54acb5
Create Date: 2025-03-05 10:00:05.006941

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "89b358b81f13"
down_revision: Union[str, None] = "8cf0fe54acb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uix_user_group_name", table_name="screener_groups")
    op.drop_index("uix_user_group_order", table_name="screener_groups")
    op.create_unique_constraint("uix_user_group_name_type", "screener_groups", ["user_id", "name", "type"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_user_group_name_type", "screener_groups", type_="unique")
    op.create_index("uix_user_group_order", "screener_groups", ["user_id", "order"], unique=True)
    op.create_index("uix_user_group_name", "screener_groups", ["user_id", "name"], unique=True)
    # ### end Alembic commands ###
