"""empty message

Revision ID: 8cf0fe54acb5
Revises:
Create Date: 2025-03-04 15:51:26.207346

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8cf0fe54acb5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "screener_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.Enum("STOCK", "ETF", "COIN", name="stocktype"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uix_user_group_name"),
        sa.UniqueConstraint("user_id", "order", name="uix_user_group_order"),
    )
    op.create_index(op.f("ix_screener_groups_id"), "screener_groups", ["id"], unique=False)
    op.create_index(op.f("ix_screener_groups_user_id"), "screener_groups", ["user_id"], unique=False)
    op.create_table(
        "screener_factor_filters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("factor", sa.String(length=50), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["screener_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_screener_factor_filters_id"), "screener_factor_filters", ["id"], unique=False)
    op.create_table(
        "screener_stock_filters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("factor", sa.String(length=50), nullable=False),
        sa.Column("above", sa.Integer(), nullable=True),
        sa.Column("below", sa.Integer(), nullable=True),
        sa.Column("value", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["screener_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_group_factor", "screener_stock_filters", ["group_id", "factor"], unique=False)
    op.create_index(op.f("ix_screener_stock_filters_id"), "screener_stock_filters", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_screener_stock_filters_id"), table_name="screener_stock_filters")
    op.drop_index("idx_group_factor", table_name="screener_stock_filters")
    op.drop_table("screener_stock_filters")
    op.drop_index(op.f("ix_screener_factor_filters_id"), table_name="screener_factor_filters")
    op.drop_table("screener_factor_filters")
    op.drop_index(op.f("ix_screener_groups_user_id"), table_name="screener_groups")
    op.drop_index(op.f("ix_screener_groups_id"), table_name="screener_groups")
    op.drop_table("screener_groups")
    # ### end Alembic commands ###
