"""empty message

Revision ID: 943de59489f5
Revises: da765efaa007
Create Date: 2025-03-12 17:04:49.507067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943de59489f5'
down_revision: Union[str, None] = 'da765efaa007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screener_sort_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('TECHNICAL', 'FUNDAMENTAL', 'VALUATION', 'DIVIDEND', 'CUSTOM', name='categoryenum'), nullable=False),
    sa.Column('sort_by', sa.String(length=50), nullable=False),
    sa.Column('ascending', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['screener_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screener_sort_infos_id'), 'screener_sort_infos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screener_sort_infos_id'), table_name='screener_sort_infos')
    op.drop_table('screener_sort_infos')
    # ### end Alembic commands ###
