"""v10

Revision ID: 98f45bac4643
Revises: bfab721b8371
Create Date: 2025-03-27 21:52:33.366499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "98f45bac4643"
down_revision: Union[str, None] = "bfab721b8371"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_using_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("product_name", sa.String(length=100), nullable=False),
        sa.Column("product_type", sa.String(length=100), nullable=False),
        sa.Column("product_relation_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("alphafinder_payment_history", sa.Column("is_extended", sa.Boolean(), nullable=False))
    op.add_column("alphafinder_user", sa.Column("using_history_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alphafinder_user", "using_history_id")
    op.drop_column("alphafinder_payment_history", "is_extended")
    op.drop_table("user_using_history")
    # ### end Alembic commands ###
