"""v25

Revision ID: 9c4fc37d4490
Revises: c2d47a25c8da
Create Date: 2025-04-28 10:26:09.160227

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c4fc37d4490"
down_revision: Union[str, None] = "c2d47a25c8da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_af_bookmarks_post_id_user_id", "af_bookmarks", ["post_id", "user_id"], unique=False)
    op.create_index("idx_af_post_likes_post_id_user_id", "af_post_likes", ["post_id", "user_id"], unique=False)
    op.add_column("af_post_reports", sa.Column("report_id", sa.Integer(), nullable=True))
    op.add_column("af_post_reports", sa.Column("content", sa.String(255), nullable=True))
    op.create_index("idx_af_posts_category_depth", "af_posts", ["category_id", "depth"], unique=False)
    op.create_index("idx_af_posts_depth_is_reported", "af_posts", ["depth", "is_reported"], unique=False)
    op.create_index("idx_af_posts_id_is_reported", "af_posts", ["id", "is_reported"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_af_posts_id_is_reported", table_name="af_posts")
    op.drop_index("idx_af_posts_depth_is_reported", table_name="af_posts")
    op.drop_index("idx_af_posts_category_depth", table_name="af_posts")
    op.drop_column("af_post_reports", "content")
    op.drop_column("af_post_reports", "report_id")
    op.drop_index("idx_af_post_likes_post_id_user_id", table_name="af_post_likes")
    op.drop_index("idx_af_bookmarks_post_id_user_id", table_name="af_bookmarks")
    # ### end Alembic commands ###
