"""v22

Revision ID: a6936076ab2c
Revises: 2c8daae59e05
Create Date: 2025-04-24 15:09:00.743449

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6936076ab2c"
down_revision: Union[str, None] = "2c8daae59e05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "af_post_likes",
        "is_liked",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        existing_comment="좋아요/싫어요 여부",
        existing_nullable=True,
    )
    op.alter_column(
        "af_post_stock_tags",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.add_column("af_posts", sa.Column("comment_count", sa.Integer(), nullable=False))
    op.alter_column(
        "af_posts", "like_count", existing_type=mysql.INTEGER(), server_default=sa.text("0"), existing_nullable=False
    )
    op.alter_column(
        "af_posts",
        "depth",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("0"),
        existing_comment="게시글 깊이",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "af_posts",
        "depth",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        existing_comment="게시글 깊이",
        existing_nullable=False,
    )
    op.alter_column(
        "af_posts", "like_count", existing_type=mysql.INTEGER(), server_default=sa.text("'0'"), existing_nullable=False
    )
    op.drop_column("af_posts", "comment_count")
    op.alter_column(
        "af_post_stock_tags",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "af_post_likes",
        "is_liked",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'1'"),
        existing_comment="좋아요/싫어요 여부",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
