"""empty message

Revision ID: b35fe23bc15f
Revises:
Create Date: 2025-03-14 19:52:24.161902

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b35fe23bc15f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "screener_sort_infos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum("TECHNICAL", "FUNDAMENTAL", "VALUATION", "DIVIDEND", "CUSTOM", name="categoryenum"),
            nullable=False,
        ),
        sa.Column("type", sa.Enum("STOCK", "ETF", "COIN", name="stocktype"), nullable=False),
        sa.Column("sort_by", sa.String(length=50), nullable=False),
        sa.Column("ascending", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["screener_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_screener_sort_infos_id"), "screener_sort_infos", ["id"], unique=False)
    op.add_column(
        "screener_factor_filters",
        sa.Column(
            "category",
            sa.Enum("TECHNICAL", "FUNDAMENTAL", "VALUATION", "DIVIDEND", "CUSTOM", name="categoryenum"),
            nullable=False,
        ),
    )
    op.alter_column(
        "screener_groups",
        "user_id",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.create_foreign_key(None, "screener_groups", "alphafinder_user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "screener_groups", type_="foreignkey")
    op.alter_column(
        "screener_groups",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.drop_column("screener_factor_filters", "category")
    op.drop_index(op.f("ix_screener_sort_infos_id"), table_name="screener_sort_infos")
    op.drop_table("screener_sort_infos")
    # ### end Alembic commands ###
