"""v24

Revision ID: c2d47a25c8da
Revises: d9b53df9c60f
Create Date: 2025-04-25 18:18:23.819742

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2d47a25c8da"
down_revision: Union[str, None] = "d9b53df9c60f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "af_post_report_items",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "af_post_reports",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_af_post_likes_created_at_post_id", "af_post_likes", ["created_at", "post_id"], unique=False)
    op.alter_column(
        "af_post_stock_tags",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.add_column("af_posts", sa.Column("is_reported", sa.Boolean(), nullable=False, comment="신고 여부"))
    op.create_index("idx_af_posts_parent_id_created_at", "af_posts", ["parent_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_af_posts_parent_id_created_at", table_name="af_posts")
    op.drop_column("af_posts", "is_reported")
    op.alter_column(
        "af_post_stock_tags",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.drop_index("idx_af_post_likes_created_at_post_id", table_name="af_post_likes")
    op.drop_table("af_post_reports")
    op.drop_table("af_post_report_items")
    # ### end Alembic commands ###
