"""v28_add_quantus_chat_tables

Revision ID: c4387c2d175a
Revises: 1c1e6b8c6ea6
Create Date: 2025-09-02 19:44:54.607699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4387c2d175a'
down_revision: Union[str, None] = '1c1e6b8c6ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quantus_chat_conversation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('preview', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('latest_job_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quantus_chat_conversation_user_id'), 'quantus_chat_conversation', ['user_id'], unique=False)
    op.create_table('quantus_chat_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('root_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['quantus_chat_conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_message_id'], ['quantus_chat_message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quantus_chat_message_conversation_id'), 'quantus_chat_message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_quantus_chat_message_root_message_id'), 'quantus_chat_message', ['root_message_id'], unique=False)
    op.create_table('quantus_chat_feedback',
    sa.Column('response_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_liked', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['quantus_chat_message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_index(op.f('ix_quantus_chat_feedback_response_id'), 'quantus_chat_feedback', ['response_id'], unique=False)
    op.create_index(op.f('ix_quantus_chat_feedback_user_id'), 'quantus_chat_feedback', ['user_id'], unique=False)
    op.alter_column('af_post_stock_tags', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('af_posts', 'content',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=False)
    op.alter_column('af_posts', 'comment_count',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('af_posts', 'depth',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_comment='게시글 깊이',
               existing_nullable=False)
    op.alter_column('alphafinder_user', 'subscription_level',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alphafinder_user', 'subscription_level',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('af_posts', 'depth',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_comment='게시글 깊이',
               existing_nullable=False)
    op.alter_column('af_posts', 'comment_count',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('af_posts', 'content',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=True)
    op.alter_column('af_post_stock_tags', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_quantus_chat_feedback_user_id'), table_name='quantus_chat_feedback')
    op.drop_index(op.f('ix_quantus_chat_feedback_response_id'), table_name='quantus_chat_feedback')
    op.drop_table('quantus_chat_feedback')
    op.drop_index(op.f('ix_quantus_chat_message_root_message_id'), table_name='quantus_chat_message')
    op.drop_index(op.f('ix_quantus_chat_message_conversation_id'), table_name='quantus_chat_message')
    op.drop_table('quantus_chat_message')
    op.drop_index(op.f('ix_quantus_chat_conversation_user_id'), table_name='quantus_chat_conversation')
    op.drop_table('quantus_chat_conversation')
    # ### end Alembic commands ###
