"""v8

Revision ID: c44843e497e8
Revises: 80266bf3a203
Create Date: 2025-03-27 09:37:02.134096

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c44843e497e8"
down_revision: Union[str, None] = "80266bf3a203"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alphafinder_coupon", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("alphafinder_coupon_box", sa.Column("coupon_name", sa.String(length=100), nullable=True))

    # Set default value for subscription_level in alphafinder_user table
    op.alter_column(
        "alphafinder_user", "subscription_level", existing_type=sa.Integer(), server_default="1", existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove default value for subscription_level in alphafinder_user table
    op.alter_column(
        "alphafinder_user", "subscription_level", existing_type=sa.Integer(), server_default=None, existing_nullable=True
    )

    op.drop_column("alphafinder_coupon_box", "coupon_name")
    op.drop_column("alphafinder_coupon", "is_active")
    # ### end Alembic commands ###
