"""v15

Revision ID: d4ce8cf6792c
Revises: e7e9e23c8c56
Create Date: 2025-04-11 11:41:00.452570

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d4ce8cf6792c"
down_revision: Union[str, None] = "e7e9e23c8c56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_download_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("data_type", sa.String(length=100), nullable=False),
        sa.Column("download_datetime", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_id", "data_download_history", ["user_id"], unique=False)
    op.create_index(
        "idx_user_id_download_datetime", "data_download_history", ["user_id", "download_datetime"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_id_download_datetime", table_name="data_download_history")
    op.drop_index("idx_user_id", table_name="data_download_history")
    op.drop_table("data_download_history")
    # ### end Alembic commands ###
