"""empty message

Revision ID: da765efaa007
Revises: 1e97d805d8c3
Create Date: 2025-03-11 10:41:17.719620

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da765efaa007"
down_revision: Union[str, None] = "1e97d805d8c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "screener_factor_filters",
        sa.Column(
            "category",
            sa.Enum("TECHNICAL", "FUNDAMENTAL", "VALUATION", "DIVIDEND", "CUSTOM", name="categoryenum"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("screener_factor_filters", "category")
    # ### end Alembic commands ###
