"""v6

Revision ID: dd55757ebda2
Revises: e07027e2604f
Create Date: 2025-03-26 16:36:52.411315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "dd55757ebda2"
down_revision: Union[str, None] = "e07027e2604f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alphafinder_coupon",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("coupon_num", sa.String(length=100), nullable=False),
        sa.Column("coupon_name", sa.String(length=100), nullable=False),
        sa.Column("coupon_period_days", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("coupon_num"),
    )
    op.create_table(
        "alphafinder_coupon_box",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("coupon_id", sa.Integer(), nullable=True),
        sa.Column("issued_at", sa.DateTime(), nullable=False, comment="지급일"),
        sa.Column("expired_at", sa.DateTime(), nullable=False, comment="만료일"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["coupon_id"], ["alphafinder_coupon.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["alphafinder_user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("alphafinder_payment_history", "is_extended")
    op.add_column("alphafinder_price", sa.Column("price_type", sa.String(length=100), nullable=False))
    op.alter_column("alphafinder_price", "event_price", existing_type=mysql.FLOAT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("alphafinder_price", "event_price", existing_type=mysql.FLOAT(), nullable=False)
    op.drop_column("alphafinder_price", "price_type")
    op.add_column(
        "alphafinder_payment_history",
        sa.Column("is_extended", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    )
    op.drop_table("alphafinder_coupon_box")
    op.drop_table("alphafinder_coupon")
    # ### end Alembic commands ###
