"""v5

Revision ID: e07027e2604f
Revises: 0298e71e4150
Create Date: 2025-03-25 09:46:43.158646

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e07027e2604f"
down_revision: Union[str, None] = "0298e71e4150"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alphafinder_level",
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("level"),
    )
    op.create_table(
        "alphafinder_price",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("period_days", sa.Integer(), nullable=False),
        sa.Column("event_price", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(
            ["level"],
            ["alphafinder_level.level"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alphafinder_payment_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("receipt_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("period_days", sa.Integer(), nullable=False),
        sa.Column("paid_amount", sa.Float(), nullable=False),
        sa.Column("payment_method", sa.String(length=100), nullable=False),
        sa.Column("payment_company", sa.String(length=100), nullable=False),
        sa.Column("is_extended", sa.Boolean(), nullable=False),
        sa.Column("refund_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(
            ["level"],
            ["alphafinder_level.level"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["alphafinder_user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "toss_receipt",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("payment_key", sa.String(length=100), nullable=False),
        sa.Column("order_id", sa.String(length=100), nullable=False),
        sa.Column("receipt", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["alphafinder_user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_key"),
    )
    op.add_column("alphafinder_user", sa.Column("subscription_start", sa.Date(), nullable=True))
    op.add_column("alphafinder_user", sa.Column("recent_payment_date", sa.Date(), nullable=True))
    op.add_column("alphafinder_user", sa.Column("subscription_level", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_user_subscription_level", "alphafinder_user", "alphafinder_level", ["subscription_level"], ["level"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_subscription_level", "alphafinder_user", type_="foreignkey")
    op.drop_column("alphafinder_user", "subscription_level")
    op.drop_column("alphafinder_user", "recent_payment_date")
    op.drop_column("alphafinder_user", "subscription_start")
    op.drop_table("toss_receipt")
    op.drop_table("alphafinder_payment_history")
    op.drop_table("alphafinder_price")
    op.drop_table("alphafinder_level")
    # ### end Alembic commands ###
