"""v19

Revision ID: e7d97c56bbac
Revises: 32368389d589
Create Date: 2025-04-22 13:38:11.788711

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7d97c56bbac"
down_revision: Union[str, None] = "32368389d589"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_conversation", sa.Column("preview", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_conversation", "preview")
    # ### end Alembic commands ###
