"""v14

Revision ID: e7e9e23c8c56
Revises: 40a22208847a
Create Date: 2025-04-03 17:51:35.187474

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e7e9e23c8c56"
down_revision: Union[str, None] = "40a22208847a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alphafinder_price", sa.Column("event_type", sa.String(length=100), nullable=True))
    op.add_column("alphafinder_price", sa.Column("event_end_date", sa.DateTime(), nullable=True))
    op.add_column("alphafinder_price", sa.Column("is_banner", sa.Boolean(), nullable=False))
    op.add_column("alphafinder_price", sa.Column("is_event", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alphafinder_price", "is_event")
    op.drop_column("alphafinder_price", "is_banner")
    op.drop_column("alphafinder_price", "event_end_date")
    op.drop_column("alphafinder_price", "event_type")
    # ### end Alembic commands ###
