"""empty message

Revision ID: efd090244289
Revises:
Create Date: 2025-03-19 17:36:37.267956

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efd090244289"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alphafinder_user", sa.Column("is_subscribed", sa.Boolean(), nullable=False))
    op.add_column("alphafinder_user", sa.Column("subscription_end", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alphafinder_user", "subscription_end")
    op.drop_column("alphafinder_user", "is_subscribed")
    # ### end Alembic commands ###
