"""empty message

Revision ID: f6044e0e242d
Revises: 241f4218b01e
Create Date: 2025-04-21 11:10:16.170555

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6044e0e242d"
down_revision: Union[str, None] = "241f4218b01e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_conversation",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("latest_job_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["alphafinder_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_conversation_user_id"), "chat_conversation", ["user_id"], unique=False)
    op.create_table(
        "chat_message",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["chat_conversation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_message_conversation_id"), "chat_message", ["conversation_id"], unique=False)
    op.alter_column(
        "alphafinder_user",
        "subscription_level",
        existing_type=mysql.INTEGER(),
        server_default=None,
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alphafinder_user",
        "subscription_level",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'1'"),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_chat_message_conversation_id"), table_name="chat_message")
    op.drop_table("chat_message")
    op.drop_index(op.f("ix_chat_conversation_user_id"), table_name="chat_conversation")
    op.drop_table("chat_conversation")
    # ### end Alembic commands ###
