"""empty message

Revision ID: fec903e65fb6
Revises: 943de59489f5
Create Date: 2025-03-12 17:23:09.426776

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fec903e65fb6"
down_revision: Union[str, None] = "943de59489f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "screener_sort_infos", sa.Column("type", sa.Enum("STOCK", "ETF", "COIN", name="stocktype"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("screener_sort_infos", "type")
    # ### end Alembic commands ###
