"""empty message

Revision ID: 343cfdbf0819
Revises: 7e73ac7acaa2
Create Date: 2024-12-27 15:04:52.563537

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "343cfdbf0819"
down_revision: Union[str, None] = "7e73ac7acaa2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("disclosure_information")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("disclosure_information")
    # ### end Alembic commands ###
