"""empty message

Revision ID: 51227869c815
Revises: 3236c8198275
Create Date: 2025-02-17 13:22:14.892241

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "51227869c815"
down_revision: Union[str, None] = "3236c8198275"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alphafinder_user",
        "profile_image",
        existing_type=mysql.VARCHAR(length=1000),
        type_=mysql.LONGTEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alphafinder_user",
        "profile_image",
        existing_type=mysql.LONGTEXT(),
        type_=mysql.VARCHAR(length=1000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
