"""empty message

Revision ID: 5da5feb1a030
Revises: 7e7040805514
Create Date: 2025-02-11 13:06:55.425497

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "5da5feb1a030"
down_revision: Union[str, None] = "7e7040805514"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_stock_interest",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("ticker", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["ticker"], ["stock_information.ticker"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["alphafinder_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_stock_interest_ticker"), "user_stock_interest", ["ticker"], unique=False)
    op.create_index(op.f("ix_user_stock_interest_user_id"), "user_stock_interest", ["user_id"], unique=False)
    op.add_column("alphafinder_user", sa.Column("provider", sa.String(length=100), nullable=False))
    op.add_column("alphafinder_user", sa.Column("profile_image", sa.String(length=1000), nullable=True))
    op.drop_column("alphafinder_user", "push_token")
    op.drop_column("alphafinder_user", "is_competing")
    op.drop_column("alphafinder_user", "magic_split_issued")
    op.drop_column("alphafinder_user", "is_relationship")
    op.drop_column("alphafinder_user", "sns_id")
    op.drop_column("alphafinder_user", "sns_type")
    op.drop_column("alphafinder_user", "is_opt_out")
    op.drop_column("alphafinder_user", "signup_platform")


def downgrade() -> None:
    op.add_column("alphafinder_user", sa.Column("signup_platform", mysql.VARCHAR(length=100), nullable=False))
    op.add_column(
        "alphafinder_user", sa.Column("is_opt_out", mysql.TINYINT(display_width=1), autoincrement=False, nullable=True)
    )
    op.add_column("alphafinder_user", sa.Column("sns_type", mysql.VARCHAR(length=100), nullable=False))
    op.add_column("alphafinder_user", sa.Column("sns_id", mysql.VARCHAR(length=1000), nullable=False))
    op.add_column(
        "alphafinder_user",
        sa.Column(
            "is_relationship",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "alphafinder_user",
        sa.Column(
            "magic_split_issued",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "alphafinder_user",
        sa.Column(
            "is_competing",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("alphafinder_user", sa.Column("push_token", mysql.TEXT(), nullable=True))
    op.drop_column("alphafinder_user", "profile_image")
    op.drop_column("alphafinder_user", "provider")
    op.drop_index(op.f("ix_user_stock_interest_user_id"), table_name="user_stock_interest")
    op.drop_index(op.f("ix_user_stock_interest_ticker"), table_name="user_stock_interest")
    op.drop_table("user_stock_interest")
    # ### end Alembic commands ###
