"""empty message

Revision ID: 6e56729ce089
Revises: 8653c716c593
Create Date: 2024-12-26 13:31:49.650012

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e56729ce089"
down_revision: Union[str, None] = "8653c716c593"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_indices",
        sa.Column("ticker", sa.String(length=100), nullable=False, comment="종목 티커"),
        sa.Column("is_open", sa.Boolean(), nullable=False, comment="장 오픈 여부"),
        sa.Column("price", sa.Float(), nullable=False, comment="현재가"),
        sa.Column("change", sa.Float(), nullable=False, comment="변동 금액"),
        sa.Column("price_rate", sa.Float(), nullable=False, comment="현재가 변동률"),
        sa.Column("rise_ratio", sa.Float(), nullable=False, comment="상승 비율"),
        sa.Column("fall_ratio", sa.Float(), nullable=False, comment="하락 비율"),
        sa.Column("unchanged_ratio", sa.Float(), nullable=False, comment="보합 비율"),
        sa.PrimaryKeyConstraint("ticker"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_indices")
    # ### end Alembic commands ###
