"""empty message

Revision ID: 72a289c55933
Revises: af37aae4abe6
Create Date: 2025-01-03 15:16:24.815028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "72a289c55933"
down_revision: Union[str, None] = "af37aae4abe6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "disclosure_information", ["filing_id"])
    op.add_column("stock_indices", sa.Column("rise_soft_ratio", sa.Float(), nullable=True, comment="약상승 비율"))
    op.add_column("stock_indices", sa.Column("fall_soft_ratio", sa.Float(), nullable=True, comment="약하락 비율"))
    op.alter_column(
        "stock_indices",
        "rise_ratio",
        existing_type=mysql.FLOAT(),
        comment="급상승 비율",
        existing_comment="상승 비율",
        existing_nullable=True,
    )
    op.alter_column(
        "stock_indices",
        "fall_ratio",
        existing_type=mysql.FLOAT(),
        comment="급하락 비율",
        existing_comment="하락 비율",
        existing_nullable=True,
    )
    op.add_column(
        "stock_information", sa.Column("sector_ko", sa.String(length=100), nullable=True, comment="최종 섹터 (한글)")
    )
    op.add_column(
        "stock_information", sa.Column("sector_en", sa.String(length=100), nullable=True, comment="최종 섹터 (영문)")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_information", "sector_en")
    op.drop_column("stock_information", "sector_ko")
    op.alter_column(
        "stock_indices",
        "fall_ratio",
        existing_type=mysql.FLOAT(),
        comment="하락 비율",
        existing_comment="급하락 비율",
        existing_nullable=True,
    )
    op.alter_column(
        "stock_indices",
        "rise_ratio",
        existing_type=mysql.FLOAT(),
        comment="상승 비율",
        existing_comment="급상승 비율",
        existing_nullable=True,
    )
    op.drop_column("stock_indices", "fall_soft_ratio")
    op.drop_column("stock_indices", "rise_soft_ratio")
    op.drop_constraint(None, "disclosure_information", type_="unique")
    # ### end Alembic commands ###
