"""v21

Revision ID: 82de6c02275a
Revises: a18dd721f2f6
Create Date: 2024-12-30 09:29:07.912818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "82de6c02275a"
down_revision: Union[str, None] = "a18dd721f2f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "disclosure_information",
        "url",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_comment="URL",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "summary",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_comment="요약",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "impact_reason",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_comment="영향 요인",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "key_points",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_comment="주요 포인트",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "en_summary",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_comment="영문 요약",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "en_impact_reason",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_comment="영문 영향 요인",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "en_key_points",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_comment="영문 주요 포인트",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "form_type",
        existing_type=mysql.VARCHAR(length=20),
        type_=sa.String(length=255),
        existing_comment="형태",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "category_type",
        existing_type=mysql.VARCHAR(length=20),
        type_=sa.String(length=255),
        existing_comment="카테고리",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "extra_info",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_comment="추가 정보",
        existing_nullable=True,
    )
    op.alter_column(
        "news_information",
        "summary",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_comment="요약",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "news_information",
        "summary",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_comment="요약",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "extra_info",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_comment="추가 정보",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "category_type",
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=20),
        existing_comment="카테고리",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "form_type",
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=20),
        existing_comment="형태",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "en_key_points",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_comment="영문 주요 포인트",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "en_impact_reason",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_comment="영문 영향 요인",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "en_summary",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_comment="영문 요약",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "key_points",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_comment="주요 포인트",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "impact_reason",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_comment="영향 요인",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "summary",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_comment="요약",
        existing_nullable=True,
    )
    op.alter_column(
        "disclosure_information",
        "url",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_comment="URL",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
