"""empty message

Revision ID: 86386d4872b2
Revises: a581c3fc98ca
Create Date: 2024-12-27 09:45:35.627782

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "86386d4872b2"
down_revision: Union[str, None] = "a581c3fc98ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alphafinder_license",
        sa.Column("serial_number", sa.String(length=100), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("plan", sa.Text(), nullable=False),
        sa.Column("expired_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("kinds", sa.String(length=100), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=False),
        sa.Column("country_type", sa.String(length=100), nullable=False),
        sa.Column("is_expired", sa.Boolean(), nullable=False),
        sa.Column("is_reserved", sa.Boolean(), nullable=False),
        sa.Column("reserve_date", sa.DateTime(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("recommender_id", sa.String(length=100), nullable=False),
        sa.Column("serial_number_related", sa.String(length=100), nullable=False),
        sa.Column("purchase_type", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("serial_number"),
    )
    op.create_table(
        "alphafinder_payment_history",
        sa.Column("payment_key", sa.String(length=100), nullable=False),
        sa.Column("order_id", sa.String(length=100), nullable=False),
        sa.Column("plan", sa.String(length=100), nullable=False),
        sa.Column("requested_at", sa.DateTime(), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=False),
        sa.Column("paid_amount", sa.Float(), nullable=False),
        sa.Column("payment_method", sa.String(length=100), nullable=False),
        sa.Column("is_refunded", sa.Boolean(), nullable=False),
        sa.Column("recommender_id", sa.String(length=100), nullable=False),
        sa.Column("is_rewarded", sa.Boolean(), nullable=False),
        sa.Column("reward_date", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_table(
        "alphafinder_user",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sns_id", sa.String(length=1000), nullable=False),
        sa.Column("sns_type", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("nickname", sa.String(length=100), nullable=False),
        sa.Column("push_token", sa.Text(), nullable=True),
        sa.Column("is_competing", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("magic_split_issued", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("is_opt_out", sa.Boolean(), nullable=True),
        sa.Column("signup_platform", sa.String(length=100), nullable=False),
        sa.Column("is_relationship", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nickname"),
    )
    op.create_table(
        "alphafinder_membership",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("license_serial_number", sa.String(length=100), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=False),
        sa.Column("expired_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["alphafinder_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "alphafinder_watchlist",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("ticker", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.ForeignKeyConstraint(["ticker"], ["stock_information.ticker"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["alphafinder_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alphafinder_watchlist_ticker"), "alphafinder_watchlist", ["ticker"], unique=False)
    op.create_index(op.f("ix_alphafinder_watchlist_user_id"), "alphafinder_watchlist", ["user_id"], unique=False)
    op.drop_index("id", table_name="news_information")
    op.drop_column("news_information", "id")
    op.add_column("stock_indices", sa.Column("date", sa.DateTime(), nullable=True, comment="날짜"))
    op.add_column("stock_indices", sa.Column("market", sa.String(length=100), nullable=True, comment="시장"))
    op.add_column(
        "stock_indices", sa.Column("included_indices", sa.String(length=100), nullable=True, comment="포함되어 있는 지수")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_indices", "included_indices")
    op.drop_column("stock_indices", "market")
    op.drop_column("stock_indices", "date")
    op.add_column(
        "news_information", sa.Column("id", mysql.BIGINT(), autoincrement=False, nullable=False, comment="뉴스 아이디")
    )
    op.create_index("id", "news_information", ["id"], unique=True)
    op.drop_index(op.f("ix_alphafinder_watchlist_user_id"), table_name="alphafinder_watchlist")
    op.drop_index(op.f("ix_alphafinder_watchlist_ticker"), table_name="alphafinder_watchlist")
    op.drop_table("alphafinder_watchlist")
    op.drop_table("alphafinder_membership")
    op.drop_table("alphafinder_user")
    op.drop_table("alphafinder_payment_history")
    op.drop_table("alphafinder_license")
    # ### end Alembic commands ###
