"""empty message

Revision ID: 9ffc758b8388
Revises: 36f57fe68763
Create Date: 2024-12-27 14:23:22.013314

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ffc758b8388"
down_revision: Union[str, None] = "36f57fe68763"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news_information", sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="뉴스 아이디")
    )
    op.create_index("idx_ticker", "news_information", ["ticker"], unique=False)
    op.create_unique_constraint(None, "news_information", ["id"])
    op.add_column("stock_trend", sa.Column("change_sign", sa.Integer(), nullable=True, comment="전일 대비 등락 부호"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_trend", "change_sign")
    op.drop_constraint(None, "news_information", type_="unique")
    op.drop_index("idx_ticker", table_name="news_information")
    op.drop_column("news_information", "id")
    # ### end Alembic commands ###
