"""v46

Revision ID: a65be9ef1074
Revises: d9fd9008fff5
Create Date: 2025-02-17 15:58:47.357185

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a65be9ef1074"
down_revision: Union[str, None] = "d9fd9008fff5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("posts", "image_url", existing_type=mysql.TEXT(), type_=mysql.LONGTEXT(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("posts", "image_url", existing_type=mysql.LONGTEXT(), type_=mysql.TEXT(), existing_nullable=True)
    # ### end Alembic commands ###
