"""empty message

Revision ID: b4c6b8fef696
Revises: a65be9ef1074
Create Date: 2025-02-17 16:18:49.289129

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b4c6b8fef696"
down_revision: Union[str, None] = "a65be9ef1074"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "factors",
        sa.Column("factor", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "unit",
            sa.Enum("PRICE", "VOLUME", "PERCENTAGE", "RATIO", "SCORE", "TIMES", "MULTIPLE", name="unitenum"),
            nullable=False,
        ),
        sa.Column("sort_direction", sa.Enum("ASC", "DESC", name="sortdirectionenum"), nullable=False),
        sa.Column("category", sa.Enum("TECHNICAL", "FUNDAMENTAL", "VALUATION", name="categoryenum"), nullable=False),
        sa.PrimaryKeyConstraint("factor"),
        sa.UniqueConstraint("factor"),
    )
    op.create_index("idx_category", "factors", ["category"], unique=False)
    op.create_index("idx_category_sort_direction", "factors", ["category", "sort_direction"], unique=False)
    op.create_index("idx_sort_direction", "factors", ["sort_direction"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_sort_direction", table_name="factors")
    op.drop_index("idx_category_sort_direction", table_name="factors")
    op.drop_index("idx_category", table_name="factors")
    op.drop_table("factors")
    # ### end Alembic commands ###
