"""v50

Revision ID: bd4225441716
Revises: ca6e44131e51
Create Date: 2025-02-18 10:16:03.115458

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bd4225441716"
down_revision: Union[str, None] = "ca6e44131e51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alphafinder_user", sa.Column("image_format", sa.String(length=20), nullable=True))
    op.add_column("posts", sa.Column("image_format", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "image_format")
    op.drop_column("alphafinder_user", "image_format")
    # ### end Alembic commands ###
