"""empty message

Revision ID: dd958799b076
Revises: 39144b24c2df
Create Date: 2024-12-18 14:40:32.076310

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "dd958799b076"
down_revision: Union[str, None] = "39144b24c2df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("stock_factor", "market_cap", existing_type=mysql.FLOAT(), nullable=True, existing_comment="시가총액")
    op.alter_column(
        "stock_factor", "shared_outstanding", existing_type=mysql.INTEGER(), nullable=True, existing_comment="상장주식수"
    )
    op.alter_column(
        "stock_factor", "last_close", existing_type=mysql.FLOAT(), nullable=True, existing_comment="전일 종가"
    )
    op.alter_column(
        "stock_factor", "week_52_high", existing_type=mysql.FLOAT(), nullable=True, existing_comment="52주 최고가"
    )
    op.alter_column(
        "stock_factor", "week_52_low", existing_type=mysql.FLOAT(), nullable=True, existing_comment="52주 최저가"
    )
    op.alter_column(
        "stock_factor",
        "finance_status",
        existing_type=mysql.INTEGER(),
        nullable=True,
        existing_comment="재무현황 (1: 좋음, 2: 보통, 3: 나쁨)",
    )
    op.alter_column(
        "stock_factor", "stock_trend", existing_type=mysql.INTEGER(), nullable=True, existing_comment="주식 추세"
    )
    op.alter_column(
        "stock_factor", "market_condition", existing_type=mysql.INTEGER(), nullable=True, existing_comment="시장 상황"
    )
    op.alter_column(
        "stock_factor", "industry_condition", existing_type=mysql.INTEGER(), nullable=True, existing_comment="업종 상황"
    )
    op.alter_column(
        "stock_information",
        "logo_image",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
        existing_comment="로고 이미지 URL",
    )
    op.alter_column(
        "stock_information", "name", existing_type=mysql.VARCHAR(length=100), nullable=True, existing_comment="종목명"
    )
    op.alter_column(
        "stock_information", "ctry", existing_type=mysql.VARCHAR(length=20), nullable=True, existing_comment="국가"
    )
    op.alter_column(
        "stock_information", "market", existing_type=mysql.VARCHAR(length=100), nullable=True, existing_comment="거래소"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_information", "market", existing_type=mysql.VARCHAR(length=100), nullable=False, existing_comment="거래소"
    )
    op.alter_column(
        "stock_information", "ctry", existing_type=mysql.VARCHAR(length=20), nullable=False, existing_comment="국가"
    )
    op.alter_column(
        "stock_information", "name", existing_type=mysql.VARCHAR(length=100), nullable=False, existing_comment="종목명"
    )
    op.alter_column(
        "stock_information",
        "logo_image",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
        existing_comment="로고 이미지 URL",
    )
    op.alter_column(
        "stock_factor", "industry_condition", existing_type=mysql.INTEGER(), nullable=False, existing_comment="업종 상황"
    )
    op.alter_column(
        "stock_factor", "market_condition", existing_type=mysql.INTEGER(), nullable=False, existing_comment="시장 상황"
    )
    op.alter_column(
        "stock_factor", "stock_trend", existing_type=mysql.INTEGER(), nullable=False, existing_comment="주식 추세"
    )
    op.alter_column(
        "stock_factor",
        "finance_status",
        existing_type=mysql.INTEGER(),
        nullable=False,
        existing_comment="재무현황 (1: 좋음, 2: 보통, 3: 나쁨)",
    )
    op.alter_column(
        "stock_factor", "week_52_low", existing_type=mysql.FLOAT(), nullable=False, existing_comment="52주 최저가"
    )
    op.alter_column(
        "stock_factor", "week_52_high", existing_type=mysql.FLOAT(), nullable=False, existing_comment="52주 최고가"
    )
    op.alter_column(
        "stock_factor", "last_close", existing_type=mysql.FLOAT(), nullable=False, existing_comment="전일 종가"
    )
    op.alter_column(
        "stock_factor", "shared_outstanding", existing_type=mysql.INTEGER(), nullable=False, existing_comment="상장주식수"
    )
    op.alter_column(
        "stock_factor", "market_cap", existing_type=mysql.FLOAT(), nullable=False, existing_comment="시가총액"
    )
    # ### end Alembic commands ###
