"""v18

Revision ID: f5a07089793f
Revises: d384518e031f
Create Date: 2024-12-27 16:38:21.785917

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f5a07089793f"
down_revision: Union[str, None] = "d384518e031f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_information", "that_time_change")
    op.drop_column("news_information", "volume_change")
    op.drop_column("news_information", "volume")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("news_information", sa.Column("volume", mysql.FLOAT(), nullable=True, comment="거래량"))
    op.add_column("news_information", sa.Column("volume_change", mysql.FLOAT(), nullable=True, comment="거래대금"))
    op.add_column(
        "news_information", sa.Column("that_time_change", mysql.FLOAT(), nullable=True, comment="해당 시간 변동률")
    )
    # ### end Alembic commands ###
