{
 "title": "FastAPI",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" },
   { "name": "service", "query": { "query": "label_values(up, job)" } },
   {
    "name": "status_code",
    "query": {
     "query": "label_values(fastapi_request_duration_seconds_count, status_code)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "FastAPI Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "5xx 오류율 (%)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 1, "y": 125 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(fastapi_request_duration_seconds_count{status_code=~\"5..\"}[$interval])) / sum(rate(fastapi_request_duration_seconds_count[$interval])) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "최근 5분 평균 응답 시간 (초)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 6, "y": 125 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(fastapi_request_duration_seconds_sum[$interval]) / rate(fastapi_request_duration_seconds_count[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "서비스 상태",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 125 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=~\"web-blue|web-green\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "총 요청 수",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 16, "y": 125 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(fastapi_request_duration_seconds_count)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic & Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "응답 시간 분위수 (초)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 1, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(fastapi_request_duration_seconds_bucket[$interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(fastapi_request_duration_seconds_bucket[$interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(fastapi_request_duration_seconds_bucket[$interval])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(fastapi_request_duration_seconds_bucket[$interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "응답 시간 분포 (초)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 35 },
     "targets": [
      {
       "expr": "sum(increase(fastapi_request_duration_seconds_bucket[$interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "초당 요청 수",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 1, "y": 82 },
     "targets": [
      {
       "expr": "sum(rate(fastapi_request_duration_seconds_count[$interval])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  { "title": "Endpoints & Status Code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "느린 엔드포인트",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 1, "y": 3 },
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.95, sum(rate(fastapi_request_duration_seconds_bucket[$interval])) by (le, path)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "상위 5개 엔드포인트",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(fastapi_request_duration_seconds_count) by (path))\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "상태 코드 분포",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 1, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fastapi_request_duration_seconds_count) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Nginx Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "총 요청 수",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 1, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nginx_http_requests_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "활성 연결",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 7, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nginx_connections_active", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Nginx 상태",
     "type": "stat",
     "gridPos": { "h": 7, "w": 9, "x": 13, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"nginx\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "초당 요청 처리율",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 1, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(nginx_http_requests_total[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "연결 처리",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 11, "y": 21 },
     "targets": [
      {
       "expr": "rate(nginx_connections_accepted[$interval])",
       "legendFormat": "Accepted"
      },
      {
       "expr": "rate(nginx_connections_handled[$interval])",
       "legendFormat": "Handled"
      }
     ]
    },
    {
     "title": "연결 상태",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 1, "y": 29 },
     "targets": [
      { "expr": "nginx_connections_reading", "legendFormat": "Reading" },
      { "expr": "nginx_connections_writing\n", "legendFormat": "Writing" },
      { "expr": "nginx_connections_waiting", "legendFormat": "Waiting" }
     ]
    }
   ]
  }
 ]
}