"""v32

Revision ID: 01939b7841d3
Revises: f3a06c92eed3
Create Date: 2025-01-22 11:08:58.156120

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01939b7841d3"
down_revision: Union[str, None] = "f3a06c92eed3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("collect_id", table_name="news_analysis")
    op.create_unique_constraint("uix_collect_id_ctry", "news_analysis", ["collect_id", "ctry"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_collect_id_ctry", "news_analysis", type_="unique")
    op.create_index("collect_id", "news_analysis", ["collect_id"], unique=True)
    # ### end Alembic commands ###
