"""v57

Revision ID: 0af78f5bc24b
Revises: 756bfe43b629
Create Date: 2025-02-25 21:59:45.058820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0af78f5bc24b"
down_revision: Union[str, None] = "756bfe43b629"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stock_information",
        sa.Column("type", sa.Enum("stock", "etf", "coin", name="stock_type"), nullable=True, comment="종목 유형"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_information", "type")
    # ### end Alembic commands ###
