"""v68

Revision ID: 129d3c24b8b2
Revises: 3c8b538355a2
Create Date: 2025-04-15 13:53:48.856905

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "129d3c24b8b2"
down_revision: Union[str, None] = "3c8b538355a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stock_information", sa.Column("is_target_etf", sa.Boolean(), nullable=True, comment="타겟 ETF 여부"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_information", "is_target_etf")
    # ### end Alembic commands ###
