"""empty message

Revision ID: 19dad30b8ced
Revises: 01939b7841d3
Create Date: 2025-02-04 16:50:27.921733

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19dad30b8ced"
down_revision: Union[str, None] = "01939b7841d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # stock_trend.is_activate 컬럼의 기본값 설정
    op.alter_column(
        "stock_trend",
        "is_activate",
        existing_type=sa.Boolean(),
        server_default=sa.text("1"),
        existing_nullable=True,
        existing_comment="사용 가능 여부",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 기본값 제거
    op.alter_column(
        "stock_trend",
        "is_activate",
        existing_type=sa.Boolean(),
        server_default=None,
        existing_nullable=True,
        existing_comment="사용 가능 여부",
    )
    # ### end Alembic commands ###
