"""empty message

Revision ID: 2073080435c9
Revises: d8624691b048
Create Date: 2025-01-07 13:09:45.861859

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2073080435c9"
down_revision: Union[str, None] = "d8624691b048"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alphafinder_user_refresh_token",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("access_token_hash", sa.String(length=64), nullable=False),
        sa.Column("refresh_token", sa.String(length=1000), nullable=False),
        sa.Column("access_token", sa.String(length=1000), nullable=False),
        sa.Column("token_data", sa.Text(), nullable=False),
        sa.Column("is_app", sa.Boolean(), server_default="0", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alphafinder_user_refresh_token_access_token_hash"),
        "alphafinder_user_refresh_token",
        ["access_token_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_alphafinder_user_refresh_token_access_token_hash"), table_name="alphafinder_user_refresh_token"
    )
    op.drop_table("alphafinder_user_refresh_token")
    # ### end Alembic commands ###
