"""v61

Revision ID: 270d93bee57a
Revises: dff5878a293c
Create Date: 2025-03-11 16:33:37.154204

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "270d93bee57a"
down_revision: Union[str, None] = "dff5878a293c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stock_information", sa.Column("is_russell_2000", sa.Boolean(), nullable=True, comment="러셀 2000 편입 여부")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_information", "is_russell_2000")
    # ### end Alembic commands ###
