"""empty message

Revision ID: 2cd5f6440caf
Revises: 962f1c2b4288
Create Date: 2025-03-27 15:53:18.715612

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cd5f6440caf"
down_revision: Union[str, None] = "962f1c2b4288"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "factors_preset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("factor", sa.String(length=50), nullable=False),
        sa.Column("min_value", sa.Integer(), nullable=True),
        sa.Column("max_value", sa.Integer(), nullable=True),
        sa.Column("text_value", sa.String(length=50), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["factor"], ["factors.factor"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("factors_preset")
    # ### end Alembic commands ###
