"""empty message

Revision ID: 30b7b492b96d
Revises: 2cd5f6440caf
Create Date: 2025-03-27 16:41:19.164385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "30b7b492b96d"
down_revision: Union[str, None] = "2cd5f6440caf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("factors_preset", sa.Column("above", sa.Integer(), nullable=True))
    op.add_column("factors_preset", sa.Column("below", sa.Integer(), nullable=True))
    op.add_column("factors_preset", sa.Column("display", sa.String(length=50), nullable=True))
    op.drop_column("factors_preset", "max_value")
    op.drop_column("factors_preset", "min_value")
    op.drop_column("factors_preset", "text_value")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    op.add_column("factors_preset", sa.Column("text_value", mysql.VARCHAR(length=50), nullable=True))
    op.add_column("factors_preset", sa.Column("min_value", mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("factors_preset", sa.Column("max_value", mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column("factors_preset", "display")
    op.drop_column("factors_preset", "below")
    op.drop_column("factors_preset", "above")
    pass
    # ### end Alembic commands ###
