"""empty message

Revision ID: 3236c8198275
Revises: 98ba7a92469a
Create Date: 2025-02-14 16:00:22.349978

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3236c8198275"
down_revision: Union[str, None] = "98ba7a92469a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alphafinder_oauth_token",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("access_token_hash", sa.String(length=64), nullable=False),
        sa.Column("refresh_token", sa.String(length=1000), nullable=False),
        sa.Column("access_token", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alphafinder_oauth_token_access_token_hash"),
        "alphafinder_oauth_token",
        ["access_token_hash"],
        unique=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alphafinder_oauth_token_access_token_hash"), table_name="alphafinder_oauth_token")
    op.drop_table("alphafinder_oauth_token")
    # ### end Alembic commands ###
