"""empty message

Revision ID: 36f57fe68763
Revises: 86386d4872b2
Create Date: 2024-12-27 13:42:19.206938

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36f57fe68763"
down_revision: Union[str, None] = "86386d4872b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_price",
        sa.Column("ticker", sa.String(length=20), nullable=False, comment="종목 코드"),
        sa.Column("market", sa.String(length=10), nullable=False, comment="시장 구분"),
        sa.Column("kr_name", sa.String(length=100), nullable=True, comment="한글 종목명"),
        sa.Column("en_name", sa.String(length=100), nullable=True, comment="영문 종목명"),
        sa.Column("execution_time", sa.DateTime(), nullable=False, comment="종목 체결 시간"),
        sa.Column("current_price", sa.Float(), nullable=False, comment="종목 현재 가격"),
        sa.Column("open", sa.Float(), nullable=False, comment="시가"),
        sa.Column("high", sa.Float(), nullable=False, comment="고가"),
        sa.Column("low", sa.Float(), nullable=False, comment="저가"),
        sa.Column("close", sa.Float(), nullable=False, comment="종가"),
        sa.Column("volume", sa.Integer(), nullable=False, comment="거래량"),
        sa.Column("change_sign", sa.Integer(), nullable=True, comment="전일 대비 등락 부호"),
        sa.Column("price_change", sa.Float(), nullable=True, comment="전일 대비"),
        sa.Column("change_rate", sa.Float(), nullable=True, comment="등락률"),
        sa.Column("volume_change", sa.Float(), nullable=True, comment="거래대금"),
        sa.PrimaryKeyConstraint("ticker"),
    )
    op.create_index(op.f("ix_stock_price_market"), "stock_price", ["market"], unique=False)
    op.add_column("disclosure_information", sa.Column("id", sa.Integer(), nullable=False, comment="ID"))
    op.add_column("disclosure_information", sa.Column("url", sa.String(length=255), nullable=True, comment="URL"))
    op.add_column(
        "disclosure_information", sa.Column("en_summary", sa.String(length=255), nullable=True, comment="영문 요약")
    )
    op.add_column(
        "disclosure_information",
        sa.Column("en_impact_reason", sa.String(length=255), nullable=True, comment="영문 영향 요인"),
    )
    op.add_column(
        "disclosure_information",
        sa.Column("en_key_points", sa.String(length=255), nullable=True, comment="영문 주요 포인트"),
    )
    op.add_column(
        "disclosure_information", sa.Column("category_type", sa.String(length=20), nullable=True, comment="카테고리")
    )
    op.add_column(
        "disclosure_information", sa.Column("extra_info", sa.String(length=255), nullable=True, comment="추가 정보")
    )
    op.create_index("idx_ticker", "disclosure_information", ["ticker"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ticker", table_name="disclosure_information")
    op.drop_column("disclosure_information", "extra_info")
    op.drop_column("disclosure_information", "category_type")
    op.drop_column("disclosure_information", "en_key_points")
    op.drop_column("disclosure_information", "en_impact_reason")
    op.drop_column("disclosure_information", "en_summary")
    op.drop_column("disclosure_information", "url")
    op.drop_column("disclosure_information", "id")
    op.drop_index(op.f("ix_stock_price_market"), table_name="stock_price")
    op.drop_table("stock_price")
    # ### end Alembic commands ###
