"""empty message

Revision ID: 39144b24c2df
Revises:
Create Date: 2024-12-18 14:14:26.518028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39144b24c2df"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_factor",
        sa.Column("ticker", sa.String(length=20), nullable=False, comment="종목 코드"),
        sa.Column("market_cap", sa.Float(), nullable=False, comment="시가총액"),
        sa.Column("shared_outstanding", sa.Integer(), nullable=False, comment="상장주식수"),
        sa.Column("last_close", sa.Float(), nullable=False, comment="전일 종가"),
        sa.Column("week_52_high", sa.Float(), nullable=False, comment="52주 최고가"),
        sa.Column("week_52_low", sa.Float(), nullable=False, comment="52주 최저가"),
        sa.Column("per", sa.Float(), nullable=True, comment="주가수익비율(PER)"),
        sa.Column("pbr", sa.Float(), nullable=True, comment="주가순자산비율(PBR)"),
        sa.Column("roe", sa.Float(), nullable=True, comment="자기자본이익률(ROE)"),
        sa.Column("finance_status", sa.Integer(), nullable=False, comment="재무현황 (1: 좋음, 2: 보통, 3: 나쁨)"),
        sa.Column("stock_trend", sa.Integer(), nullable=False, comment="주식 추세"),
        sa.Column("market_condition", sa.Integer(), nullable=False, comment="시장 상황"),
        sa.Column("industry_condition", sa.Integer(), nullable=False, comment="업종 상황"),
        sa.PrimaryKeyConstraint("ticker"),
    )
    op.create_table(
        "stock_information",
        sa.Column("ticker", sa.String(length=20), nullable=False, comment="종목 티커"),
        sa.Column("logo_image", sa.String(length=255), nullable=False, comment="로고 이미지 URL"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="종목명"),
        sa.Column("ctry", sa.String(length=20), nullable=False, comment="국가"),
        sa.Column("market", sa.String(length=100), nullable=False, comment="거래소"),
        sa.Column("is_kospi_100", sa.Boolean(), nullable=True, comment="코스피 100 편입 여부"),
        sa.Column("is_kospi_150", sa.Boolean(), nullable=True, comment="코스피 150 편입 여부"),
        sa.Column("is_kospi_200", sa.Boolean(), nullable=True, comment="코스피 200 편입 여부"),
        sa.Column("is_kosdaq_150", sa.Boolean(), nullable=True, comment="코스닥 150 편입 여부"),
        sa.Column("is_krx_300", sa.Boolean(), nullable=True, comment="KRX 300 편입 여부"),
        sa.Column("is_snp_500", sa.Boolean(), nullable=True, comment="S&P 500 편입 여부"),
        sa.Column("is_nasdaq_100", sa.Boolean(), nullable=True, comment="나스닥 100 편입 여부"),
        sa.Column("sector_1", sa.String(length=100), nullable=True, comment="GICS Level 1 (11개 섹터)"),
        sa.Column("sector_2", sa.String(length=100), nullable=True, comment="GICS Level 2 (25개 섹터)"),
        sa.Column("sector_3", sa.String(length=100), nullable=True, comment="GICS Level 3 (74개 섹터)"),
        sa.Column("sector_4", sa.String(length=100), nullable=True, comment="GICS Level 4 (163개 섹터)"),
        sa.Column("homepage_url", sa.String(length=255), nullable=True, comment="회사 홈페이지 URL"),
        sa.Column("ceo", sa.String(length=100), nullable=True, comment="대표이사"),
        sa.Column("establishment_date", sa.Date(), nullable=True, comment="설립일"),
        sa.Column("listing_date", sa.Date(), nullable=False, comment="상장일"),
        sa.PrimaryKeyConstraint("ticker"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_information")
    op.drop_table("stock_factor")
    # ### end Alembic commands ###
