"""v67

Revision ID: 3c8b538355a2
Revises: c5fd95b5aa14
Create Date: 2025-04-11 11:13:50.223614

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c8b538355a2"
down_revision: Union[str, None] = "c5fd95b5aa14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_indices_1d",
        sa.Column("ticker", sa.String(length=10), nullable=False, comment="종목 티커"),
        sa.Column("date", sa.DateTime(), nullable=False, comment="날짜"),
        sa.Column("open", sa.Float(), nullable=True, comment="시가"),
        sa.Column("high", sa.Float(), nullable=True, comment="고가"),
        sa.Column("low", sa.Float(), nullable=True, comment="저가"),
        sa.Column("close", sa.Float(), nullable=True, comment="종가"),
        sa.Column("volume", sa.Float(), nullable=True, comment="거래량"),
        sa.PrimaryKeyConstraint("ticker", "date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_indices_1d")
    # ### end Alembic commands ###
