"""empty message

Revision ID: 3cca2cfca633
Revises: 9ffc758b8388
Create Date: 2024-12-27 14:40:53.182178

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cca2cfca633"
down_revision: Union[str, None] = "9ffc758b8388"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("news_information")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("news_information")
    # ### end Alembic commands ###
