"""v58

Revision ID: 3ee90101b08f
Revises: 0af78f5bc24b
Create Date: 2025-02-26 16:43:23.401103

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ee90101b08f"
down_revision: Union[str, None] = "0af78f5bc24b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "etf_kr_1d",
        sa.Column("Ticker", sa.String(length=20), nullable=False),
        sa.Column("Date", sa.DateTime(), nullable=True),
        sa.Column("Open", sa.Float(), nullable=True),
        sa.Column("High", sa.Float(), nullable=True),
        sa.Column("Low", sa.Float(), nullable=True),
        sa.Column("Close", sa.Float(), nullable=True),
        sa.Column("Volume", sa.Float(), nullable=True),
        sa.Column("Bid", sa.Float(), nullable=True),
        sa.Column("Ask", sa.Float(), nullable=True),
        sa.Column("Market", sa.String(length=20), nullable=True),
        sa.Column("Market_Cap", sa.Float(), nullable=True),
        sa.Column("NumShrs", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("Ticker", "Date"),
    )
    op.create_table(
        "etf_us_1d",
        sa.Column("Ticker", sa.String(length=20), nullable=False),
        sa.Column("Date", sa.DateTime(), nullable=True),
        sa.Column("Open", sa.Float(), nullable=True),
        sa.Column("High", sa.Float(), nullable=True),
        sa.Column("Low", sa.Float(), nullable=True),
        sa.Column("Close", sa.Float(), nullable=True),
        sa.Column("Volume", sa.Float(), nullable=True),
        sa.Column("Bid", sa.Float(), nullable=True),
        sa.Column("Ask", sa.Float(), nullable=True),
        sa.Column("Market", sa.String(length=20), nullable=True),
        sa.Column("Market_Cap", sa.Float(), nullable=True),
        sa.Column("NumShrs", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("Ticker", "Date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("etf_us_1d")
    op.drop_table("etf_kr_1d")
    # ### end Alembic commands ###
