"""empty message

Revision ID: 4274e57e4ef9
Revises: 6de92f63bde8
Create Date: 2025-02-06 20:18:26.993635

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4274e57e4ef9"
down_revision: Union[str, None] = "6de92f63bde8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_indices_1m",
        sa.Column("ticker", sa.String(length=10), nullable=False, comment="종목 티커"),
        sa.Column("date", sa.DateTime(), nullable=True, comment="날짜"),
        sa.Column("open", sa.Float(), nullable=True, comment="시가"),
        sa.Column("high", sa.Float(), nullable=True, comment="고가"),
        sa.Column("low", sa.Float(), nullable=True, comment="저가"),
        sa.Column("close", sa.Float(), nullable=True, comment="종가"),
        sa.Column("volume", sa.Float(), nullable=True, comment="거래량"),
        sa.Column("change", sa.Float(), nullable=True, comment="변동 금액"),
        sa.Column("change_rate", sa.Float(), nullable=True, comment="변동률"),
        sa.PrimaryKeyConstraint("ticker", "date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_indices_1m")
    # ### end Alembic commands ###
