"""empty message

Revision ID: 46cee821f04c
Revises: 93d6f26d41c3
Create Date: 2024-12-26 15:20:13.958529

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46cee821f04c"
down_revision: Union[str, None] = "93d6f26d41c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disclosure_information",
        sa.Column("ticker", sa.String(length=20), nullable=False, comment="종목 티커"),
        sa.Column("ko_name", sa.String(length=100), nullable=True, comment="종목 한글명"),
        sa.Column("en_name", sa.String(length=100), nullable=True, comment="종목 영문명"),
        sa.Column("ctry", sa.String(length=20), nullable=True, comment="국가"),
        sa.Column("date", sa.DateTime(), nullable=True, comment="날짜, 시간"),
        sa.Column("title", sa.String(length=255), nullable=True, comment="제목"),
        sa.Column("summary", sa.String(length=255), nullable=True, comment="요약"),
        sa.Column("impact_reason", sa.String(length=255), nullable=True, comment="영향 요인"),
        sa.Column("key_points", sa.String(length=255), nullable=True, comment="주요 포인트"),
        sa.Column("emotion", sa.String(length=20), nullable=True, comment="감정"),
        sa.Column("form_type", sa.String(length=20), nullable=True, comment="형태"),
        sa.Column("that_time_price", sa.Float(), nullable=True, comment="해당 시간 종가"),
        sa.Column("that_time_change", sa.Float(), nullable=True, comment="해당 시간 변동률"),
        sa.Column("volume", sa.Float(), nullable=True, comment="거래량"),
        sa.Column("volume_change", sa.Float(), nullable=True, comment="거래대금"),
        sa.Column("is_top_story", sa.Boolean(), nullable=True, comment="주요 소식 선정 여부"),
        sa.Column("is_exist", sa.Boolean(), nullable=True, comment="DB 존재 여부"),
        sa.PrimaryKeyConstraint("ticker"),
    )
    op.create_index("idx_ctry_date", "disclosure_information", ["ctry", "date"], unique=False)
    op.create_index("idx_ticker_ctry", "disclosure_information", ["ticker", "ctry"], unique=False)
    op.create_index("idx_ticker_date", "disclosure_information", ["ticker", "date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ticker_date", table_name="disclosure_information")
    op.drop_index("idx_ticker_ctry", table_name="disclosure_information")
    op.drop_index("idx_ctry_date", table_name="disclosure_information")
    op.drop_table("disclosure_information")
    # ### end Alembic commands ###
