"""empty message

Revision ID: 4dc46f0cb561
Revises: c361d4bc30b6
Create Date: 2025-04-02 16:06:36.747344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4dc46f0cb561"
down_revision: Union[str, None] = "c361d4bc30b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("factors_preset", sa.Column("value", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("factors_preset", "value")
    # ### end Alembic commands ###
