"""empty message

Revision ID: 4fe8cb01849b
Revises: 2c3dda97574f
Create Date: 2025-02-21 18:04:53.182733

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4fe8cb01849b"
down_revision: Union[str, None] = "2c3dda97574f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("factors", sa.Column("min_value", sa.Numeric(), nullable=True))
    op.add_column("factors", sa.Column("max_value", sa.Numeric(), nullable=True))
    op.add_column("factors", sa.Column("is_stock", sa.Boolean(), nullable=False))
    op.add_column("factors", sa.Column("is_etf", sa.Boolean(), nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("factors", "is_etf")
    op.drop_column("factors", "is_stock")
    op.drop_column("factors", "max_value")
    op.drop_column("factors", "min_value")
    # ### end Alembic commands ###
