"""v54

Revision ID: 54adea236048
Revises: ad484f328258
Create Date: 2025-02-19 14:44:30.161584

"""

from typing import Sequence, Union

from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54adea236048"
down_revision: Union[str, None] = "ad484f328258"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dividend_information", "id", existing_type=mysql.INTEGER(), autoincrement=True, existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dividend_information", "id", existing_type=mysql.INTEGER(), autoincrement=False, existing_nullable=False
    )
    # ### end Alembic commands ###
