"""empty message

Revision ID: 6de92f63bde8
Revises: 19dad30b8ced
Create Date: 2025-02-05 09:29:47.081835

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6de92f63bde8"
down_revision: Union[str, None] = "19dad30b8ced"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing primary key
    op.drop_constraint("dividend_information_pkey", "dividend_information", type_="primary")

    # Make ex_date not nullable
    op.alter_column(
        "dividend_information", "ex_date", existing_type=sa.DATE(), nullable=False, existing_comment="배당 락일"
    )

    # Add new composite primary key
    op.create_primary_key("dividend_information_pkey", "dividend_information", ["ticker", "ex_date"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop composite primary key
    op.drop_constraint("dividend_information_pkey", "dividend_information", type_="primary")

    # Make ex_date nullable again
    op.alter_column(
        "dividend_information", "ex_date", existing_type=sa.DATE(), nullable=True, existing_comment="배당 락일"
    )

    # Restore original primary key on ticker
    op.create_primary_key("dividend_information_pkey", "dividend_information", ["ticker"])
    # ### end Alembic commands ###
