"""v19

Revision ID: 72e94d47a217
Revises: f5a07089793f
Create Date: 2024-12-27 19:34:51.352892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "72e94d47a217"
down_revision: Union[str, None] = "f5a07089793f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("disclosure_information", "that_time_change")
    op.drop_column("disclosure_information", "volume_change")
    op.drop_column("disclosure_information", "volume")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("disclosure_information", sa.Column("volume", mysql.FLOAT(), nullable=True, comment="거래량"))
    op.add_column("disclosure_information", sa.Column("volume_change", mysql.FLOAT(), nullable=True, comment="거래대금"))
    op.add_column(
        "disclosure_information", sa.Column("that_time_change", mysql.FLOAT(), nullable=True, comment="해당 시간 변동률")
    )
    # ### end Alembic commands ###
