"""empty message

Revision ID: 756bfe43b629
Revises: 4fe8cb01849b
Create Date: 2025-02-23 15:36:29.483994

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "756bfe43b629"
down_revision: Union[str, None] = "4fe8cb01849b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "factors",
        "min_value",
        existing_type=mysql.DECIMAL(precision=10, scale=0),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "factors",
        "max_value",
        existing_type=mysql.DECIMAL(precision=10, scale=0),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "factors",
        "max_value",
        existing_type=sa.Integer(),
        type_=mysql.DECIMAL(precision=10, scale=0),
        existing_nullable=True,
    )
    op.alter_column(
        "factors",
        "min_value",
        existing_type=sa.Integer(),
        type_=mysql.DECIMAL(precision=10, scale=0),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
