"""empty message

Revision ID: 7e7040805514
Revises: 4274e57e4ef9
Create Date: 2025-02-10 18:29:53.096236

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e7040805514"
down_revision: Union[str, None] = "4274e57e4ef9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news_analysis",
        sa.Column("is_related", sa.Boolean(), server_default=sa.true(), nullable=True, comment="관련 종목 여부"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_analysis", "is_related")
    # ### end Alembic commands ###
