"""empty message

Revision ID: 7e73ac7acaa2
Revises: 3cca2cfca633
Create Date: 2024-12-27 14:43:49.057618

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e73ac7acaa2"
down_revision: Union[str, None] = "3cca2cfca633"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("disclosure_information")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("disclosure_information")
    # ### end Alembic commands ###
