"""empty message

Revision ID: 80cf02567b4b
Revises: dd958799b076
Create Date: 2024-12-18 18:52:44.981616

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80cf02567b4b"
down_revision: Union[str, None] = "dd958799b076"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stock_information", sa.Column("kr_name", sa.String(length=100), nullable=True, comment="한글 종목명"))
    op.add_column("stock_information", sa.Column("en_name", sa.String(length=100), nullable=True, comment="영문 종목명"))
    op.alter_column(
        "stock_information", "listing_date", existing_type=sa.DATE(), nullable=True, existing_comment="상장일"
    )
    op.drop_column("stock_information", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stock_information", sa.Column("name", mysql.VARCHAR(length=100), nullable=True, comment="종목명"))
    op.alter_column(
        "stock_information", "listing_date", existing_type=sa.DATE(), nullable=False, existing_comment="상장일"
    )
    op.drop_column("stock_information", "en_name")
    op.drop_column("stock_information", "kr_name")
    # ### end Alembic commands ###
