"""v59
Revision ID: 83b6d0226340
Revises: 3ee90101b08f
Create Date: 2025-02-26 16:58:10.213627
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "83b6d0226340"
down_revision: Union[str, None] = "3ee90101b08f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("etf_kr_1d", sa.Column("MarketCap", sa.Float(), nullable=True))
    op.drop_column("etf_kr_1d", "Market_Cap")
    op.add_column("etf_us_1d", sa.Column("MarketCap", sa.Float(), nullable=True))
    op.drop_column("etf_us_1d", "Market_Cap")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("etf_us_1d", sa.Column("Market_Cap", mysql.FLOAT(), nullable=True))
    op.drop_column("etf_us_1d", "MarketCap")
    op.add_column("etf_kr_1d", sa.Column("Market_Cap", mysql.FLOAT(), nullable=True))
    op.drop_column("etf_kr_1d", "MarketCap")
    # ### end Alembic commands ###
