"""empty message

Revision ID: 8653c716c593
Revises: 80cf02567b4b
Create Date: 2024-12-26 09:39:52.624571

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8653c716c593"
down_revision: Union[str, None] = "80cf02567b4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dividend_information",
        sa.Column("ticker", sa.String(length=20), nullable=False, comment="종목 티커"),
        sa.Column("payment_date", sa.Date(), nullable=True, comment="배당 지급일"),
        sa.Column("ex_date", sa.Date(), nullable=True, comment="배당 락일"),
        sa.Column("per_share", sa.Float(), nullable=True, comment="1주당 배당금"),
        sa.Column("per_share_rate", sa.Float(), nullable=True, comment="1주당 배당비율"),
        sa.Column("growth_rate", sa.Float(), nullable=True, comment="배당 성장률"),
        sa.Column("yield_rate", sa.Float(), nullable=True, comment="배당 수익률"),
        sa.PrimaryKeyConstraint("ticker"),
    )
    op.create_table(
        "news_information",
        sa.Column("ticker", sa.String(length=20), nullable=False, comment="종목 티커"),
        sa.Column("ko_name", sa.String(length=100), nullable=True, comment="종목 한글명"),
        sa.Column("en_name", sa.String(length=100), nullable=True, comment="종목 영문명"),
        sa.Column("is_news", sa.Boolean(), nullable=True, comment="뉴스 여부 (True: 뉴스, False: 공시)"),
        sa.Column("date", sa.DateTime(), nullable=True, comment="날짜, 시간"),
        sa.Column("title", sa.String(length=255), nullable=True, comment="제목"),
        sa.Column("summary", sa.String(length=255), nullable=True, comment="요약"),
        sa.Column("emotion", sa.String(length=20), nullable=True, comment="감정"),
        sa.Column("that_time_price", sa.Float(), nullable=True, comment="해당 시간 종가"),
        sa.Column("that_time_change", sa.Float(), nullable=True, comment="해당 시간 변동률"),
        sa.Column("volume", sa.Float(), nullable=True, comment="거래량"),
        sa.Column("volume_change", sa.Float(), nullable=True, comment="거래대금"),
        sa.Column("is_top_story", sa.Boolean(), nullable=True, comment="주요 소식 선정 여부"),
        sa.PrimaryKeyConstraint("ticker"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("news_information")
    op.drop_table("dividend_information")
    # ### end Alembic commands ###
