"""empty message

Revision ID: 93d6f26d41c3
Revises: 9ebe31bade74
Create Date: 2024-12-26 15:14:25.666656

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "93d6f26d41c3"
down_revision: Union[str, None] = "9ebe31bade74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("news_information", sa.Column("ctry", sa.String(length=20), nullable=True, comment="국가"))
    op.add_column("news_information", sa.Column("is_exist", sa.Boolean(), nullable=True, comment="DB 존재 여부"))
    op.create_index("idx_ctry_date", "news_information", ["ctry", "date"], unique=False)
    op.create_index("idx_ticker_ctry", "news_information", ["ticker", "ctry"], unique=False)
    op.create_index("idx_ticker_date", "news_information", ["ticker", "date"], unique=False)
    op.drop_column("news_information", "is_news")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news_information",
        sa.Column(
            "is_news",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
            comment="뉴스 여부 (True: 뉴스, False: 공시)",
        ),
    )
    op.drop_index("idx_ticker_date", table_name="news_information")
    op.drop_index("idx_ticker_ctry", table_name="news_information")
    op.drop_index("idx_ctry_date", table_name="news_information")
    op.drop_column("news_information", "is_exist")
    op.drop_column("news_information", "ctry")
    # ### end Alembic commands ###
