"""empty message

Revision ID: 962f1c2b4288
Revises: bb03454f8a2a
Create Date: 2025-03-26 13:16:52.414864

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "962f1c2b4288"
down_revision: Union[str, None] = "bb03454f8a2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("factors", sa.Column("is_active", sa.Boolean(), nullable=False))


def downgrade() -> None:
    op.drop_column("factors", "is_active")
    # ### end Alembic commands ###
