"""empty message

Revision ID: 9ebe31bade74
Revises: 6e56729ce089
Create Date: 2024-12-26 13:33:58.701695

"""

from typing import Sequence, Union

from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ebe31bade74"
down_revision: Union[str, None] = "6e56729ce089"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_indices",
        "is_open",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
        existing_comment="장 오픈 여부",
    )
    op.alter_column("stock_indices", "price", existing_type=mysql.FLOAT(), nullable=True, existing_comment="현재가")
    op.alter_column("stock_indices", "change", existing_type=mysql.FLOAT(), nullable=True, existing_comment="변동 금액")
    op.alter_column(
        "stock_indices", "price_rate", existing_type=mysql.FLOAT(), nullable=True, existing_comment="현재가 변동률"
    )
    op.alter_column(
        "stock_indices", "rise_ratio", existing_type=mysql.FLOAT(), nullable=True, existing_comment="상승 비율"
    )
    op.alter_column(
        "stock_indices", "fall_ratio", existing_type=mysql.FLOAT(), nullable=True, existing_comment="하락 비율"
    )
    op.alter_column(
        "stock_indices", "unchanged_ratio", existing_type=mysql.FLOAT(), nullable=True, existing_comment="보합 비율"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_indices", "unchanged_ratio", existing_type=mysql.FLOAT(), nullable=False, existing_comment="보합 비율"
    )
    op.alter_column(
        "stock_indices", "fall_ratio", existing_type=mysql.FLOAT(), nullable=False, existing_comment="하락 비율"
    )
    op.alter_column(
        "stock_indices", "rise_ratio", existing_type=mysql.FLOAT(), nullable=False, existing_comment="상승 비율"
    )
    op.alter_column(
        "stock_indices", "price_rate", existing_type=mysql.FLOAT(), nullable=False, existing_comment="현재가 변동률"
    )
    op.alter_column("stock_indices", "change", existing_type=mysql.FLOAT(), nullable=False, existing_comment="변동 금액")
    op.alter_column("stock_indices", "price", existing_type=mysql.FLOAT(), nullable=False, existing_comment="현재가")
    op.alter_column(
        "stock_indices",
        "is_open",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
        existing_comment="장 오픈 여부",
    )
    # ### end Alembic commands ###
