"""empty message

Revision ID: a18dd721f2f6
Revises: 72e94d47a217
Create Date: 2024-12-27 20:50:16.039704

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a18dd721f2f6"
down_revision: Union[str, None] = "72e94d47a217"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_trend",
        "last_updated",
        existing_type=mysql.DATETIME(),
        nullable=True,
        existing_comment="마지막 업데이트 시간",
    )
    op.alter_column(
        "stock_trend", "market", existing_type=mysql.VARCHAR(length=10), nullable=True, existing_comment="시장 구분"
    )
    op.alter_column("stock_trend", "current_price", existing_type=mysql.FLOAT(), nullable=True, existing_comment="현재가")
    op.alter_column("stock_trend", "prev_close", existing_type=mysql.FLOAT(), nullable=True, existing_comment="전일종가")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("stock_trend", "prev_close", existing_type=mysql.FLOAT(), nullable=False, existing_comment="전일종가")
    op.alter_column(
        "stock_trend", "current_price", existing_type=mysql.FLOAT(), nullable=False, existing_comment="현재가"
    )
    op.alter_column(
        "stock_trend", "market", existing_type=mysql.VARCHAR(length=10), nullable=False, existing_comment="시장 구분"
    )
    op.alter_column(
        "stock_trend",
        "last_updated",
        existing_type=mysql.DATETIME(),
        nullable=False,
        existing_comment="마지막 업데이트 시간",
    )
    # ### end Alembic commands ###
