"""v53

Revision ID: ad484f328258
Revises: b8c2faee7ce3
Create Date: 2025-02-19 14:25:49.489024

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad484f328258"
down_revision: Union[str, None] = "b8c2faee7ce3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("PRIMARY", "dividend_information", type_="primary")
    op.create_primary_key("pk_dividend_information", "dividend_information", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("pk_dividend_information", "dividend_information", type_="primary")
    op.create_primary_key("PRIMARY", "dividend_information", ["ticker", "ex_date"])
    # ### end Alembic commands ###
