"""v23

Revision ID: af37aae4abe6
Revises: b08a3c3fe21c
Create Date: 2025-01-02 16:03:43.858634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "af37aae4abe6"
down_revision: Union[str, None] = "b08a3c3fe21c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "disclosure_information", sa.Column("filing_id", sa.String(length=255), nullable=True, comment="파일링 ID")
    )
    op.alter_column(
        "stock_trend", "change_rt", existing_type=mysql.FLOAT(), comment="실시간 등락률", existing_nullable=True
    )
    op.alter_column(
        "stock_trend", "change_1m", existing_type=mysql.FLOAT(), comment="1개월 등락률", existing_nullable=True
    )
    op.alter_column(
        "stock_trend", "change_6m", existing_type=mysql.FLOAT(), comment="6개월 등락률", existing_nullable=True
    )
    op.alter_column(
        "stock_trend", "volume_rt", existing_type=mysql.FLOAT(), comment="1분 거래량 비율", existing_nullable=True
    )
    op.alter_column(
        "stock_trend", "volume_1m", existing_type=mysql.FLOAT(), comment="1개월 거래량 비율", existing_nullable=True
    )
    op.alter_column(
        "stock_trend", "volume_6m", existing_type=mysql.FLOAT(), comment="6개월 거래량 비율", existing_nullable=True
    )
    op.alter_column(
        "stock_trend", "volume_change_rt", existing_type=mysql.FLOAT(), comment="1분 거래대금", existing_nullable=True
    )
    op.alter_column(
        "stock_trend", "volume_change_1m", existing_type=mysql.FLOAT(), comment="1개월 거래대금", existing_nullable=True
    )
    op.alter_column(
        "stock_trend", "volume_change_6m", existing_type=mysql.FLOAT(), comment="6개월 거래대금", existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_trend",
        "volume_change_6m",
        existing_type=mysql.FLOAT(),
        comment=None,
        existing_comment="6개월 거래대금",
        existing_nullable=True,
    )
    op.alter_column(
        "stock_trend",
        "volume_change_1m",
        existing_type=mysql.FLOAT(),
        comment=None,
        existing_comment="1개월 거래대금",
        existing_nullable=True,
    )
    op.alter_column(
        "stock_trend",
        "volume_change_rt",
        existing_type=mysql.FLOAT(),
        comment=None,
        existing_comment="1분 거래대금",
        existing_nullable=True,
    )
    op.alter_column(
        "stock_trend",
        "volume_6m",
        existing_type=mysql.FLOAT(),
        comment=None,
        existing_comment="6개월 거래량 비율",
        existing_nullable=True,
    )
    op.alter_column(
        "stock_trend",
        "volume_1m",
        existing_type=mysql.FLOAT(),
        comment=None,
        existing_comment="1개월 거래량 비율",
        existing_nullable=True,
    )
    op.alter_column(
        "stock_trend",
        "volume_rt",
        existing_type=mysql.FLOAT(),
        comment=None,
        existing_comment="1분 거래량 비율",
        existing_nullable=True,
    )
    op.alter_column(
        "stock_trend",
        "change_6m",
        existing_type=mysql.FLOAT(),
        comment=None,
        existing_comment="6개월 등락률",
        existing_nullable=True,
    )
    op.alter_column(
        "stock_trend",
        "change_1m",
        existing_type=mysql.FLOAT(),
        comment=None,
        existing_comment="1개월 등락률",
        existing_nullable=True,
    )
    op.alter_column(
        "stock_trend",
        "change_rt",
        existing_type=mysql.FLOAT(),
        comment=None,
        existing_comment="실시간 등락률",
        existing_nullable=True,
    )
    op.drop_column("disclosure_information", "filing_id")
    # ### end Alembic commands ###
