"""v28

Revision ID: af578dd20a44
Revises: c9c805a07c4f
Create Date: 2025-01-05 18:02:48.122184

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af578dd20a44"
down_revision: Union[str, None] = "c9c805a07c4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("news_information", sa.Column("links", sa.Text(), nullable=True, comment="링크"))
    op.alter_column(
        "stock_trend", "kr_name", existing_type=mysql.VARCHAR(length=100), comment="종목 한글명", existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_trend",
        "kr_name",
        existing_type=mysql.VARCHAR(length=100),
        comment=None,
        existing_comment="종목 한글명",
        existing_nullable=True,
    )
    op.drop_column("news_information", "links")
    # ### end Alembic commands ###
