"""empty message

Revision ID: afe536976229
Revises: 46cee821f04c
Create Date: 2024-12-26 17:25:52.981045

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afe536976229"
down_revision: Union[str, None] = "46cee821f04c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news_information", sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="뉴스 아이디")
    )
    op.create_unique_constraint(None, "news_information", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "news_information", type_="unique")
    op.drop_column("news_information", "id")
    # ### end Alembic commands ###
