"""v52

Revision ID: b8c2faee7ce3
Revises: bba4a210e33c
Create Date: 2025-02-19 14:20:11.448998

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8c2faee7ce3"
down_revision: Union[str, None] = "bba4a210e33c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dividend_information", sa.Column("id", sa.Integer(), autoincrement=True, nullable=False))
    op.create_index("idx_ticker_ex_date", "dividend_information", ["ticker", "ex_date"], unique=False)
    op.create_unique_constraint(
        "uix_ticker_ex_date_payment_date", "dividend_information", ["ticker", "ex_date", "payment_date"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_ticker_ex_date_payment_date", "dividend_information", type_="unique")
    op.drop_index("idx_ticker_ex_date", table_name="dividend_information")
    op.drop_column("dividend_information", "id")
    # ### end Alembic commands ###
