"""v62

Revision ID: bb03454f8a2a
Revises: 270d93bee57a
Create Date: 2025-03-13 17:21:26.741501

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb03454f8a2a"
down_revision: Union[str, None] = "270d93bee57a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("disclosure_information", sa.Column("lang", sa.String(length=20), nullable=True, comment="언어"))
    op.drop_index("filing_id", table_name="disclosure_information")
    op.create_unique_constraint("uq_filing_id_lang", "disclosure_information", ["filing_id", "lang"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_filing_id_lang", "disclosure_information", type_="unique")
    op.create_index("filing_id", "disclosure_information", ["filing_id"], unique=True)
    op.drop_column("disclosure_information", "lang")
    # ### end Alembic commands ###
