"""v51

Revision ID: bba4a210e33c
Revises: bd4225441716
Create Date: 2025-02-19 13:27:33.804329

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bba4a210e33c"
down_revision: Union[str, None] = "bd4225441716"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dividend_information", "growth_rate")
    op.drop_column("dividend_information", "per_share_rate")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dividend_information", sa.Column("per_share_rate", mysql.FLOAT(), nullable=True, comment="1주당 배당비율")
    )
    op.add_column("dividend_information", sa.Column("growth_rate", mysql.FLOAT(), nullable=True, comment="배당 성장률"))
    # ### end Alembic commands ###
