"""empty message

Revision ID: c361d4bc30b6
Revises: 30b7b492b96d
Create Date: 2025-04-02 15:55:46.582108

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "c361d4bc30b6"
down_revision: Union[str, None] = "30b7b492b96d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "factors", sa.Column("type", sa.Enum("SLIDER", "MULTI", "SINGLE", name="factortypeenum"), nullable=False)
    )
    op.alter_column(
        "factors",
        "category",
        existing_type=mysql.ENUM("technical", "fundamental", "valuation", "dividend", "growth"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "factors",
        "category",
        existing_type=mysql.ENUM("technical", "fundamental", "valuation", "dividend", "growth"),
        nullable=True,
    )
    op.drop_column("factors", "type")
    # ### end Alembic commands ###
