"""v69

Revision ID: c5d8c488672f
Revises: 129d3c24b8b2
Create Date: 2025-04-16 17:35:25.711612

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5d8c488672f"
down_revision: Union[str, None] = "129d3c24b8b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "etf_top_holdings",
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("top_holdings", sa.String(length=20), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.PrimaryKeyConstraint("ticker", "top_holdings"),
        sa.CheckConstraint("weight >= 0 AND weight <= 100", name="weight_range_check"),
    )
    op.create_index("idx_ticker", "etf_top_holdings", ["ticker"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ticker", table_name="etf_top_holdings")
    op.drop_table("etf_top_holdings")
    # ### end Alembic commands ###
