"""v66

Revision ID: c5fd95b5aa14
Revises: 30b7b492b96d
Create Date: 2025-04-10 11:25:47.853475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c5fd95b5aa14"
down_revision: Union[str, None] = "30b7b492b96d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("factors", sa.Column("order", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("factors", "order")
    # ### end Alembic commands ###
