"""v69

Revision ID: c65854f64677
Revises: 129d3c24b8b2
Create Date: 2025-04-17 17:12:45.273623

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c65854f64677"
down_revision: Union[str, None] = "129d3c24b8b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "etf_top_holdings",
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("holding_ticker", sa.String(length=20), nullable=True),
        sa.Column("isin", sa.String(length=30), nullable=True),
        sa.Column("shares", sa.Float(), nullable=True),
        sa.Column("weight", sa.Float(), sa.CheckConstraint("weight >= 0 AND weight <= 100"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "holding_ticker"),
    )
    op.create_index("idx_ticker", "etf_top_holdings", ["ticker"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ticker", table_name="etf_top_holdings")
    op.drop_table("etf_top_holdings")
    # ### end Alembic commands ###
