"""v49

Revision ID: ca6e44131e51
Revises: 8ee765996f7a
Create Date: 2025-02-17 20:11:37.391821

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca6e44131e51"
down_revision: Union[str, None] = "8ee765996f7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uix_collect_id_lang", table_name="news_analysis")
    op.create_unique_constraint("uix_collect_id_ctry_lang", "news_analysis", ["collect_id", "ctry", "lang"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_collect_id_ctry_lang", "news_analysis", type_="unique")
    op.create_index("uix_collect_id_lang", "news_analysis", ["collect_id", "lang"], unique=True)
    # ### end Alembic commands ###
