"""empty message

Revision ID: d8624691b048
Revises: af578dd20a44
Create Date: 2025-01-06 13:15:31.844219

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8624691b048"
down_revision: Union[str, None] = "af578dd20a44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stock_information", sa.Column("can_use", sa.Boolean(), nullable=True, comment="사용 가능 여부"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_information", "can_use")
    # ### end Alembic commands ###
