"""empty message

Revision ID: d9fd9008fff5
Revises: 51227869c815
Create Date: 2025-02-17 15:18:15.159879

"""

from typing import Sequence, Union

from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9fd9008fff5"
down_revision: Union[str, None] = "51227869c815"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("comments", "user_id", existing_type=mysql.BIGINT(), nullable=True)
    op.drop_constraint("comments_ibfk_3", "comments", type_="foreignkey")
    op.create_foreign_key(None, "comments", "alphafinder_user", ["user_id"], ["id"], ondelete="SET NULL")
    op.alter_column("posts", "user_id", existing_type=mysql.BIGINT(), nullable=True)
    op.drop_constraint("posts_ibfk_2", "posts", type_="foreignkey")
    op.create_foreign_key(None, "posts", "alphafinder_user", ["user_id"], ["id"], ondelete="SET NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.create_foreign_key("posts_ibfk_2", "posts", "alphafinder_user", ["user_id"], ["id"])
    op.alter_column("posts", "user_id", existing_type=mysql.BIGINT(), nullable=False)
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key("comments_ibfk_3", "comments", "alphafinder_user", ["user_id"], ["id"])
    op.alter_column("comments", "user_id", existing_type=mysql.BIGINT(), nullable=False)
    # ### end Alembic commands ###
