"""v60

Revision ID: dff5878a293c
Revises: 83b6d0226340
Create Date: 2025-03-07 11:48:22.108540

"""

from typing import Sequence, Union

from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dff5878a293c"
down_revision: Union[str, None] = "83b6d0226340"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "factors",
        "category",
        existing_type=mysql.ENUM("technical", "fundamental", "valuation"),
        type_=mysql.ENUM("technical", "fundamental", "valuation", "dividend"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "factors",
        "category",
        existing_type=mysql.ENUM("technical", "fundamental", "valuation", "dividend"),
        type_=mysql.ENUM("technical", "fundamental", "valuation"),
        nullable=True,
    )
    # ### end Alembic commands ###
