"""v70

Revision ID: e94c37669065
Revises: c65854f64677
Create Date: 2025-04-17 18:53:05.335464

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e94c37669065"
down_revision: Union[str, None] = "c65854f64677"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("etf_top_holdings", sa.Column("name", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("etf_top_holdings", "name")
    # ### end Alembic commands ###
