"""v31

Revision ID: f3a06c92eed3
Revises: 2073080435c9
Create Date: 2025-01-21 21:01:45.080003

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3a06c92eed3"
down_revision: Union[str, None] = "2073080435c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_analysis",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="뉴스 아이디"),
        sa.Column("collect_id", sa.BigInteger(), nullable=True, comment="수집 아이디"),
        sa.Column("ticker", sa.String(length=20), nullable=True, comment="종목 티커"),
        sa.Column("kr_name", sa.String(length=100), nullable=True, comment="종목 한글명"),
        sa.Column("en_name", sa.String(length=100), nullable=True, comment="종목 영문명"),
        sa.Column("ctry", sa.String(length=20), nullable=True, comment="국가"),
        sa.Column("date", sa.DateTime(), nullable=True, comment="날짜, 시간"),
        sa.Column("title", sa.String(length=255), nullable=True, comment="제목"),
        sa.Column("emotion", sa.String(length=20), nullable=True, comment="시장 영향"),
        sa.Column("summary", sa.Text(), nullable=True, comment="한글 요약"),
        sa.Column("impact_reason", sa.Text(), nullable=True, comment="한글 영향 이유"),
        sa.Column("key_points", sa.Text(), nullable=True, comment="한글 주요 포인트"),
        sa.Column("en_summary", sa.Text(), nullable=True, comment="영문 요약"),
        sa.Column("en_impact_reason", sa.Text(), nullable=True, comment="영문 영향 이유"),
        sa.Column("en_key_points", sa.Text(), nullable=True, comment="영문 주요 포인트"),
        sa.Column("related_tickers", sa.Text(), nullable=True, comment="관련 종목"),
        sa.Column("url", sa.Text(), nullable=True, comment="URL"),
        sa.Column("that_time_price", sa.Float(), nullable=True, comment="해당 시간 종가"),
        sa.Column("is_top_story", sa.Boolean(), nullable=True, comment="주요 소식 선정 여부"),
        sa.Column("is_exist", sa.Boolean(), nullable=True, comment="DB 존재 여부"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("collect_id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index("idx_ctry_date", "news_analysis", ["ctry", "date"], unique=False)
    op.create_index("idx_ticker", "news_analysis", ["ticker"], unique=False)
    op.create_index("idx_ticker_ctry", "news_analysis", ["ticker", "ctry"], unique=False)
    op.create_index("idx_ticker_date", "news_analysis", ["ticker", "date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ticker_date", table_name="news_analysis")
    op.drop_index("idx_ticker_ctry", table_name="news_analysis")
    op.drop_index("idx_ticker", table_name="news_analysis")
    op.drop_index("idx_ctry_date", table_name="news_analysis")
    op.drop_table("news_analysis")
    # ### end Alembic commands ###
