"""empty message

Revision ID: f89618352bf3
Revises: 2d6a81803318
Create Date: 2025-02-13 14:22:56.070587

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f89618352bf3"
down_revision: Union[str, None] = "2d6a81803318"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stock_trend", sa.Column("is_cared", sa.Boolean(), nullable=True, comment="관리종목 여부"))
    op.add_column("stock_trend", sa.Column("is_warned", sa.Boolean(), nullable=True, comment="경고종목 여부"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_trend", "is_warned")
    op.drop_column("stock_trend", "is_cared")
    # ### end Alembic commands ###
