"""empty message

Revision ID: ff900c578387
Revises: 1d32b2a15829
Create Date: 2025-01-03 16:32:47.515095

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff900c578387"
down_revision: Union[str, None] = "1d32b2a15829"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_information", "sector_en")
    op.alter_column("stock_trend", "ctry", existing_type=mysql.VARCHAR(length=20), comment="국가", existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_trend",
        "ctry",
        existing_type=mysql.VARCHAR(length=20),
        comment=None,
        existing_comment="국가",
        existing_nullable=True,
    )
    op.add_column(
        "stock_information", sa.Column("sector_en", mysql.VARCHAR(length=100), nullable=True, comment="최종 섹터 (영문)")
    )
    # ### end Alembic commands ###
