DOCUMENT_TYPE_MAPPING = {  #
    # 수시공시
    "8-K": "주요 이벤트 공시",
    "6-K": "외국기업 수시공시",
    # 지분 및 인수 관련
    "SC 13D": "5% 이상 지분 취득 (적극 투자)",
    "SC 13G": "5% 이상 지분 취득 (단순 투자)",
    "SC 14D1": "공개매수 신고",
    "SC 13E3": "비공개기업 전환 공시",
    "SC 13E4": "자사주 매입 공시",
    # 정기보고서
    "10-Q": "분기 실적 보고서",
    "13F-E": "기관투자 포트폴리오 보고서",
    "10-K": "연간 실적 보고서",
    "20-F": "외국기업 연간 실적 보고서",
    "11-K": "직원 주식매수제도 보고서",
    # 증권 등록
    "S-1": "신규 증권 등록 신청",
    "S-3": "간소화 증권 등록 신청",
    "424B": "증권신고서 수정본",
    "425": "합병 및 인수 공시",
    # 위험신호
    "NT 10-K": "연간보고서 지연 공시",
    "NT 10-Q": "분기보고서 지연 공시",
    # 주주총회/의결권
    "DEF14A": "주주총회 소집 통지",
    "DEFA14A": "추가 위임장 공시",
    "DEFM14A": "합병 관련 위임장 공시",
}

DOCUMENT_TYPE_MAPPING_EN = {
    # 수시공시
    "8-K": "Current Report",
    "6-K": "Report of Foreign Private Issuer",
    # 지분 및 인수 관련
    "SC 13D": "Beneficial Ownership Report (Active)",
    "SC 13G": "Beneficial Ownership Report (Passive)",
    "SC 14D1": "Tender Offer Statement",
    "SC 13E3": "Going-Private Transaction Statement",
    "SC 13E4": "Issuer Tender Offer Statement",
    # 정기보고서
    "10-Q": "Quarterly Report",
    "13F-E": "Institutional Investment Manager Holdings Report",
    "10-K": "Annual Report",
    "20-F": "Annual Report by Foreign Private Issuer",
    "11-K": "Annual Report of Employee Stock Purchase, Savings and Similar Plans",
    # 증권 등록
    "S-1": "Registration Statement",
    "S-3": "Registration Statement (Simplified)",
    "424B": "Prospectus Filed Pursuant to Rule 424(b)",
    "425": "Filing under Rule 425 (Business Combination)",
    # 위험신호
    "NT 10-K": "Notification of Late Filing (Annual)",
    "NT 10-Q": "Notification of Late Filing (Quarterly)",
    # 주주총회/의결권
    "DEF14A": "Definitive Proxy Statement",
    "DEFA14A": "Additional Definitive Proxy Materials",
    "DEFM14A": "Definitive Proxy Statement for Merger",
}

CATEGORY_TYPE_MAPPING_EN = {
    "기재정정": "Amended Filing",  # 기존 제출 내용(기재사항)을 수정/정정하는 경우
    "발행조건확정": "Issuance Terms Finalized",  # 채권·주식 등 발행 시 최종 조건이 확정됨
    "연장결정": "Extension Determined",  # 만기·기한 등 기존 일정을 연장하기로 결정
    "첨부정정": "Amended Attachment",  # 첨부 서류(첨부파일) 내용을 정정 또는 수정
}


FORM_TYPE_MAPPING = {
    "감사보고서": "Audit Report",
    "감사보고서제출": "Submission of Audit Report",
    "감사전재무제표기한내미제출신고서": "Filing of Non-Submission of Pre-Audit Financial Statements",
    "감자결정": "Decision on Capital Reduction",
    "감자완료": "Completion of Capital Reduction",
    "거래처와의거래중단": "Suspension of Transactions with Business Partner",
    "결산실적공시예고": "Pre-Announcement of Settlement Results Disclosure",
    "경영권변경등에관한계약체결": "Contract on Changes in Management Control, etc.",
    "경영정상화계획의이행약정체결": "Agreement on Implementing Management Normalization Plan",
    "계열금융회사의약관에의한금융거래-": "Financial Transactions under Affiliated Financial Company's Terms",
    "계열금융회사를거래상대방으로한단기금융상품거래의분기별공시": "Quarterly Disclosure of Short-Term Financial Transactions with Affiliated Financial Company",
    "계열회사변경": "Change in Affiliated Companies",
    "공개매수결과보고서": "Public Tender Offer Result Report",
    "공개매수설명서": "Public Tender Offer Prospectus",
    "공개매수신고서": "Public Tender Offer Registration Statement",
    "공정거래자율준수프로그램운영현황": "Status of Fair Trade Compliance Program",
    "기타경영사항": "Other Management-Related Matters",
    "기타시장안내": "Other Market Announcements",
    "기타안내사항": "Other Notices",
    "기타주요경영사항": "Other Major Business Issues",
    "기업가치제고계획": "Corporate Value Enhancement Plan",
    "기업가치제고계획예고": "Advance Notice of Corporate Value Enhancement Plan",
    "기업설명회개최": "Holding of IR (Investor Relations) Session",
    "기업설명회개최결과": "Results of IR (Investor Relations) Session",
    "기업인수목적회사관련합병취소ㆍ부인사실발생": "Merger Cancellation/Denial Related to SPAC",
    "기업인수목적회사의예치ㆍ신탁계약내용변경": "Change of Deposit/Trust Contract for SPAC",
    "기업인수목적회사의임원선임결정": "Decision on Executive Appointment for SPAC",
    "내부결산시점관리종목지정ㆍ형식적상장폐지ㆍ상장적격성실질심사사유발생": "Designation as Administrative Issue at Closing, Formal Delisting, or Trigger of Listing Eligibility Review",
    "단기차입금감소결정": "Decision to Decrease Short-Term Borrowings",
    "단기차입금증가결정": "Decision to Increase Short-Term Borrowings",
    "단일판매ㆍ공급계약체결": "Signing of Single Sales/Supply Contract",
    "단일판매ㆍ공급계약해지": "Termination of Single Sales/Supply Contract",
    "대규모기업집단현황공시": "Disclosure of Large Enterprise Group Status",
    "대출원리금연체사실발생": "Occurrence of Loan Principal & Interest Delinquency",
    "동일인등출자계열회사와의상품ㆍ용역거래": "Goods/Services Transactions with Affiliated Companies of the Same Controlling Shareholder",
    "동일인등출자계열회사와의상품ㆍ용역거래변경": "Change in Goods/Services Transactions with Affiliated Companies of the Same Controlling Shareholder",
    "등록취소요건해소": "Resolution of Delisting Grounds",  # (원문 목록엔 없으나 예시로...)
    "반기보고서": "Semi-Annual Report",
    "배당락": "Ex-Dividend",
    "벌금등의부과": "Imposition of Fines, etc.",
    "본점소재지변경": "Change of Headquarters Location",
    "불성실공시법인미지정": "Not Designated as Unfaithful Disclosure Company",
    "불성실공시법인지정": "Designation as Unfaithful Disclosure Company",
    "불성실공시법인지정예고": "Advance Notice of Designation as Unfaithful Disclosure Company",
    "분기보고서": "Quarterly Report",
    "분산요건미달": "Failure to Meet Distribution Requirements",
    "분산요건미달해소": "Resolution of Failure to Meet Distribution Requirements",
    "비적정감사보고서": "Non-Unqualified Audit Report",  # (만약 목록에 있으면
    "사외이사의선임ㆍ해임또는중도퇴임에관한신고": "Report on Appointment/Dismissal or Resignation of Outside Directors",
    "사채권자집회결의": "Resolution of Bondholders' Meeting",
    "사채권자집회소집": "Convening of Bondholders' Meeting",
    "사업보고서": "Business Report",
    "상각형조건부자본증권발행결정": "Decision to Issue Write-Down Contingent Capital Securities",
    "상장채권관련기타주요사항": "Other Key Matters Related to Listed Bonds",
    "상호변경안내": "Notification of Name Change",
    "소각결정": "Decision on Share Retirement",  # (주식소각결정과 유사
    "소액공모공시서류": "Small-Scale Public Offering Disclosure Documents",
    "소액공모실적보고서": "Small-Scale Public Offering Performance Report",
    "소속부변경": "Change in Listing Division",
    "소송등의제기ㆍ신청": "Filing of Lawsuit, etc.",
    "소송등의판결ㆍ결정": "Court Ruling or Decision on Lawsuit, etc.",
    "수시공시의무관련사항": "Matters Related to Ad-Hoc Disclosure Obligations",
    "신규시설투자등": "New Facility Investments, etc.",
    "신주인수권부사채발행후만기전사채취득": "Redemption of BW (Bond with Warrant) Before Maturity after Issuance",
    "신주인수권부사채행사가액의조정": "Adjustment of Exercise Price for Bond with Warrant",
    "신주인수권행사": "Exercise of Subscription Warrants",
    "신주인수권행사가액의조정": "Adjustment of Warrant Exercise Price",
    "신탁계약해지결과보고서": "Report on Termination of Trust Contract",
    "신탁계약에의한취득상황보고서": "Acquisition Status Report under Trust Contract",
    "심리프로세스": "Deliberation Process",  # (목록에 없으면 제외...
    "약관에의한금융거래시계열금융회사의거래상대방의공시": "Disclosure of Affiliated Financial Company as Counterparty in Contract-Based Financial Transactions",
    "양수도계약해지": "Termination of Transfer Contract",  # (목록에 없으면 제외...
    "어음ㆍ채권발행관련": "Note/Bond Issuance Related",  # (목록에 없으면 제외...
    "업무중단": "Suspension of Business",  # (목록에 없으면 제외...
    "영업양도결정": "Decision on Business Transfer",
    "영업양수결정": "Decision on Business Acquisition",
    "영업정지": "Suspension of Business Operations",
    "영업실적등에대한전망": "Forecast of Operating Results, etc.",
    "연결감사보고서": "Consolidated Audit Report",
    "연결재무제표기준영업실적": "Operating Performance Based on Consolidated Financial Statements",
    "연결재무제표기준영업실적등에대한전망": "Forecast of Operating Performance Based on Consolidated Financial Statements",
    "예비심사": "Preliminary Review",  # (목록에 없으면 제외...
    "의결권대리행사권유에관한의견표명서": "Statement of Opinions on Proxy Solicitation",
    "의결권대리행사권유참고서류": "Reference Documents for Proxy Solicitation",
    "임상시험단계진입ㆍ종료": "Initiation/Completion of Clinical Trial Phase",
    "임시주주총회결과": "Results of Extraordinary General Meeting of Shareholders",
    "임원ㆍ주요주주특정증권등거래계획보고서": "Report on Trading Plans of Specific Securities by Directors/Major Shareholders",
    "임원ㆍ주요주주특정증권등거래계획철회보고서": "Report on Withdrawal of Trading Plans of Specific Securities by Directors/Major Shareholders",
    "임원ㆍ주요주주특정증권등소유상황보고서": "Report on Holdings of Specific Securities by Directors/Major Shareholders",
    "자기교환사채만기전취득결정": "Decision to Redeem Own Exchangeable Bonds Before Maturity",
    "자기전환사채만기전취득결정": "Decision to Redeem Own Convertible Bonds Before Maturity",
    "자기주식취득결과보고서": "Report on Results of Treasury Stock Acquisition",
    "자기주식취득결정": "Decision to Acquire Treasury Shares",
    "자기주식처분결과보고서": "Report on Results of Disposal of Treasury Shares",
    "자본잠식50%이상또는매출액50억원미만사실발생": "Occurrence of Over 50% Capital Erosion or Less Than 5 Billion KRW in Sales",
    "자산재평가결과": "Results of Asset Revaluation",
    "자산재평가실시결정": "Decision to Conduct Asset Revaluation",
    "장래사업ㆍ경영계획": "Future Business/Management Plans",
    "재해발생": "Occurrence of Disaster",
    "전환가액의조정": "Adjustment of Conversion Price",
    "전환가액ㆍ신주인수권행사가액ㆍ교환가액의조정": "Adjustment of Conversion/Subscription/Exchange Price",
    "전환사채발행후만기전사채취득": "Redemption of Convertible Bonds Before Maturity after Issuance",
    "전환주식의전환가액조정": "Adjustment of Conversion Price of Convertible Shares",
    "전환주식의전환청구권행사": "Exercise of Conversion Right of Convertible Shares",
    "전환청구권ㆍ신주인수권ㆍ교환청구권행사": "Exercise of Conversion, Warrant, or Exchange Rights",
    "전환청구권행사": "Exercise of Conversion Right",
    "점포폐쇄": "Closure of Branches/Stores",  # (목록에 없으면 제외...
    "정기주주총회결과": "Results of Regular General Meeting of Shareholders",
    "정정신고서제출요구": "Request for Filing of Amended Registration Statement",
    "주권매매거래정지": "Suspension of Stock Trading",
    "주권매매거래정지기간변경": "Change in Period of Stock Trading Suspension",
    "주권매매거래정지해제": "Lifting of Stock Trading Suspension",
    "주권관련사채권의처분결정": "Decision on Disposal of Equity-Linked Bonds",
    "주권관련사채권의취득결정": "Decision on Acquisition of Equity-Linked Bonds",
    "주주명부폐쇄기간또는기준일설정": "Setting of Period or Record Date for Shareholder Registry Closure",
    "주주총회소집결의": "Resolution to Convene General Meeting of Shareholders",
    "주주총회소집공고": "Notice of General Meeting of Shareholders",
    "주주총회집중일개최사유신고": "Report on Reasons for Holding Shareholders' Meeting on Concentrated Date",
    "주식배당결정": "Decision on Stock Dividend",
    "주식병합결정": "Decision on Reverse Stock Split",
    "주식분할결정": "Decision on Stock Split",
    "주식소각결정": "Decision on Retirement of Shares",
    "주식매수선택권부여에관한신고": "Report on Grant of Stock Options",
    "주식매수선택권행사": "Exercise of Stock Options",
    "주식등의대량보유상황보고서": "Large Shareholding Report",
    "중간배당을위한주주명부폐쇄결정": "Decision to Close Shareholder Registry for Interim Dividend",
    "증권발행결과": "Results of Securities Issuance",
    "증권발행실적보고서": "Securities Issuance Performance Report",
    "증권신고서": "Securities Registration Statement",
    "증권예탁증권발행결정": "Decision on Issuance of Depositary Receipts",
    "지급수단별ㆍ지급기간별지급금액및분쟁조정기구에관한사항": "Payment Amount by Method/Period and Dispute Resolution Body",
    "지속가능경영보고서등관련사항": "Matters Related to Sustainability Management Report, etc.",
    "지정자문인선임계약의변경": "Change in Designated Advisor Appointment Contract",
    "지정자문인선임계약의해지": "Termination of Designated Advisor Appointment Contract",
    "지주회사의자회사편입": "Inclusion of Subsidiary in Holding Company",
    "지주회사의자회사편입ㆍ탈퇴": "Inclusion/Exclusion of Subsidiary in Holding Company",
    "지주회사의자회사탈퇴": "Exclusion of Subsidiary from Holding Company",
    "차입금액의확대": "Increase in Borrowings",  # (목록에 없으면 제외...
    "채무면제결정": "Decision on Debt Exemption",
    "채무인수결정": "Decision on Assumption of Debt",
    "철회신고서": "Withdrawal Registration Statement",
    "최대주주등소유주식변동신고서": "Report on Changes in Shareholding of Major Shareholders, etc.",
    "최대주주변경": "Change in Largest Shareholder",
    "최대주주변경을수반하는주식담보제공계약개시": "Commencement of Share Pledge Contract Involving Change in Largest Shareholder",  # (부분적 추가…
    "최대주주변경을수반하는주식담보제공계약해제ㆍ취소등": "Cancellation of Share Pledge Contract Involving Change in Largest Shareholder",
    "최대주주변경을수반하는주식양수도계약체결": "Share Transfer Contract Involving Change in Largest Shareholder",
    "최대주주변경을수반하는주식양수도계약해제ㆍ취소등": "Termination/Cancellation of Share Transfer Contract Involving Change in Largest Shareholder",
    "최대주주인명목회사·조합등의최대주주변경": "Change in Largest Shareholder of a Nominal Company/Association as Largest Shareholder",
    "최대주주인명목회사의최대주주변경": "Change in Largest Shareholder of a Nominal Holding Company",
    "투자설명서": "Investment Prospectus",
    "투자유의안내": "Investment Caution Notice",
    "투자판단관련주요경영사항": "Key Management Matters for Investment Decision",
    "파산신청": "Filing for Bankruptcy",
    "파산신청기각": "Dismissal of Bankruptcy Filing",
    "파생상품거래손실발생": "Occurrence of Derivatives Trading Loss",
    "풍문또는보도에대한해명": "Clarification on Rumor or Media Report",
    "피보증법인회생절차및파산관련신청": "Application for Rehabilitation or Bankruptcy of Guaranteed Entity",
    "횡령ㆍ배임사실확인": "Confirmation of Embezzlement/Breach of Trust",
    "횡령ㆍ배임혐의발생": "Occurrence of Embezzlement/Breach of Trust Suspicion",
    "횡령ㆍ배임혐의진행사항": "Progress of Embezzlement/Breach of Trust Allegations",
    "회계처리기준위반에따른검찰고발등조치": "Prosecutorial Action, etc. due to Violation of Accounting Standards",
    "회계처리기준위반에따른검찰고발등조치결과": "Result of Prosecutorial Action, etc. due to Violation of Accounting Standards",
    "회계처리기준위반에따른임원의해임권고조치": "Recommendation to Dismiss Executives due to Violation of Accounting Standards",
    "회계처리기준위반행위로인한증권선물위원회의검찰고발등": "Prosecutorial Charges by Securities & Futures Commission due to Violation of Accounting Standards",
    "회생절차개시결정": "Decision on Commencement of Rehabilitation Proceedings",
    "회생절차개시신청": "Filing for Commencement of Rehabilitation Proceedings",
    "회생절차개시신청기각": "Dismissal of Application for Commencement of Rehabilitation Proceedings",
    "회생절차폐지결정": "Decision to Terminate Rehabilitation Proceedings",
    "효력발생안내": "Notice of Effectuation",
    # -------------------------------
    # 이하, '특수관계인/부동산투자회사' 등 세부항목들
    # -------------------------------
    "부동산투자회사금전배당결정": "Decision on Monetary Dividend for REIT",
    "부동산투자회사부동산개발사업투자ㆍ운용": "Investment/Operation in Real Estate Development by REIT",
    "부동산투자회사부동산취득": "Acquisition of Real Estate by REIT",
    "부동산투자회사부동산처분": "Disposition of Real Estate by REIT",
    "부동산투자회사부동산임대": "Real Estate Lease by REIT",
    "부동산투자회사자금차입": "Borrowing of Funds by REIT",
    "부동산투자회사자산관리위탁계약해지": "Termination of Asset Management Entrustment Contract for REIT",
    "부동산투자회사자산보관위탁계약변경": "Change in Asset Custody Entrustment Contract for REIT",
    "부동산투자회사자산보관위탁계약체결": "Conclusion of Asset Custody Entrustment Contract for REIT",
    "부동산투자회사증권취득": "Acquisition of Securities by REIT",
    "생산재개": "Resumption of Production",
    "생산중단": "Suspension of Production",
    "선급금지급결정": "Decision on Payment of Advance",
    "외국지주회사의자회사편입ㆍ탈퇴": "Inclusion/Exclusion of Subsidiary in Foreign Holding Company",
    "유동성공급계약의체결": "Execution of Liquidity Provision Agreement",
    "유상증자1차발행가액결정": "Decision on First Issuance Price in Paid-in Capital Increase",
    "유상증자결정": "Decision on Paid-in Capital Increase",
    "유상증자또는주식관련사채등의발행결과": "Results of Paid-in Capital Increase or Issuance of Equity-Linked Securities",
    "유상증자또는주식관련사채등의청약결과": "Subscription Results of Paid-in Capital Increase or Equity-Linked Securities",
    "유상증자신주발행가액": "Issue Price of New Shares for Paid-in Capital Increase",
    "유상증자최종발행가액확정": "Final Determination of Issue Price for Paid-in Capital Increase",
    "조회공시요구": "Request for Inquiry Disclosure",
    "조회공시요구에대한답변": "Response to Inquiry Disclosure Request",
    "특수관계인과의보험거래": "Insurance Transactions with Related Party",
    "특수관계인과의수익증권거래": "Investment Trust Transactions with Related Party",
    "특수관계인과의예ㆍ적금거래": "Deposit/Savings Transactions with Related Party",
    "특수관계인과의내부거래": "Internal Transactions with Related Party",
    "특수관계인에대한기타유가증권매도": "Sale of Other Marketable Securities to Related Party",
    "특수관계인에대한주식의처분": "Disposition of Shares to Related Party",
    "특수관계인에대한채권매도": "Sale of Bonds to Related Party",
    "특수관계인에대한담보제공": "Provision of Collateral to Related Party",
    "특수관계인에대한부동산매도": "Sale of Real Estate to Related Party",
    "특수관계인에대한부동산임대": "Lease of Real Estate to Related Party",
    "특수관계인에대한자금대여": "Loan of Funds to Related Party",
    "특수관계인에대한자산양도": "Transfer of Assets to Related Party",
    "특수관계인에대한증여": "Donation/Gift to Related Party",
    "특수관계인으로부터기타유가증권매수": "Purchase of Other Marketable Securities from Related Party",
    "특수관계인으로부터부동산매수": "Purchase of Real Estate from Related Party",
    "특수관계인으로부터부동산임차": "Lease of Real Estate from Related Party",
    "특수관계인으로부터받은담보": "Collateral Received from Related Party",
    "특수관계인으로부터자금차입": "Borrowing of Funds from Related Party",
    "특수관계인으로부터자산양수": "Acquisition of Assets from Related Party",
    "특수관계인으로부터채권매수": "Purchase of Bonds from Related Party",
    "특수관계인으로부터영업양수": "Acquisition of Business from Related Party",
    "특수관계인으로부터유가증권차입": "Borrowing of Securities from Related Party",
    "특수관계인의유상증자참여": "Participation of Related Party in Paid-in Capital Increase",
    "타법인주식및출자증권처분결정": "Decision on Disposal of Stocks and Equity of Another Company",
    "타법인주식및출자증권취득결정": "Decision on Acquisition of Stocks and Equity of Another Company",
    "타인에대한담보제공결정": "Decision on Providing Collateral for Third Party",
    "타인에대한채무보증결정": "Decision on Providing Debt Guarantee for Third Party",
    # 교환사채(CB) 관련
    "교환사채발행후만기전사채취득": "Acquisition of Exchangeable Bonds before Maturity after Issuance",
    "교환가액의조정": "Adjustment of Exchange Price",
    "교환청구권행사": "Exercise of Exchange Right",
    # 권리락
    "권리락": "Ex-Rights (Ex-Date for Rights)",
    # 회사합병 / 분할합병 / 분할
    "회사합병결정": "Decision on Merger",
    "회사분할합병결정": "Decision on Spin-Off Merger",
    "회사분할결정": "Decision on Spin-Off",
    "합병등종료보고서": "Completion Report of Merger, etc.",
    # 매출액/손익구조 변동 관련
    "매출액또는손익구조30%이상변경": "Change of 30% or More in Revenue or Profit Structure",
    "매출액또는손익구조30%미만변경": "Change of Less Than 30% in Revenue or Profit Structure",
    "매출채권이외의채권에서발생한손상차손": "Impairment Loss Arising from Non-Trade Receivables",
    # 최대주주변경 관련
    "최대주주변경을수반하는주식담보제공계약체결": "Execution of Share Pledge Contract Involving Change in Largest Shareholder",
    # 특허권
    "특허권취득": "Acquisition of Patent",
    # 해외증권거래소
    "해외증권거래소등에신고한주요공시사항의국내신고": "Domestic Filing of Major Disclosure Items Reported to Overseas Stock Exchange, etc.",
    # 매매거래정지 및 해제
    "매매거래정지및정지해제": "Trading Suspension and Resumption",
    # 배당
    "현금ㆍ현물배당결정": "Decision on Cash or In-Kind Dividend",
    "현금ㆍ현물배당을위한주주명부폐쇄결정": "Decision to Close Shareholder Registry for Cash or In-Kind Dividend",
    # 대표이사 변경
    "대표이사변경": "Change of Representative Director (CEO)",
    # 일괄신고
    "일괄신고서": "Shelf Registration Statement (Batch Registration)",
    "일괄신고추가서류": "Additional Documents for Shelf Registration",
    # 기업지배구조보고서
    "기업지배구조보고서공시": "Disclosure of Corporate Governance Report",
    # 유형자산
    "유형자산처분결정": "Decision on Disposal of Tangible Assets",
    "유형자산취득결정": "Decision on Acquisition of Tangible Assets",
    # 주요사항보고서 (괄호 포함된 항목은 동일 취급)
    "주요사항보고서": "Major Issues Report",
    "주요사항보고서)": "Major Issues Report (possible typo with extra parenthesis)",
    # 해산
    "해산사유발생": "Occurrence of Grounds for Dissolution",
    # 금전대여
    "금전대여결정": "Decision on Lending Funds",
    # 특수관계인 관련 (출자, 주식 취득)
    "특수관계인에대한출자": "Equity Investment in Related Party",
    "특수관계인으로부터주식의취득": "Acquisition of Shares from Related Party",
}
