name: Deploy Service

on:
  pull_request:
    types: [closed]
    branches:
      - staging
      - dev
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
      clean_cache:
        description: 'Clean pip/poetry cache'
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Determine environment
        id: determine-env
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
            echo "CLEAN_CACHE=${{ github.event.inputs.clean_cache }}" >> $GITHUB_ENV
          elif [ "${{ github.base_ref }}" == "staging" ] || [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "CLEAN_CACHE=false" >> $GITHUB_ENV
          elif [ "${{ github.base_ref }}" == "dev" ] || [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
            echo "CLEAN_CACHE=false" >> $GITHUB_ENV
          else
            echo "Unsupported branch for deployment"
            exit 1
          fi

      - name: Set environment-specific variables
        id: set-env-vars
        run: |
          if [ "${{ env.ENVIRONMENT }}" == "staging" ]; then
            echo "SERVER_HOST=${{ secrets.STAGING_SERVER_HOST }}" >> $GITHUB_ENV
            echo "SSH_USER=${{ secrets.STAGING_SSH_USER }}" >> $GITHUB_ENV
            echo "::set-output name=ssh_key::STAGING_SSH_PRIVATE_KEY"
          else  # default to dev
            echo "SERVER_HOST=${{ secrets.DEV_SERVER_HOST }}" >> $GITHUB_ENV
            echo "SSH_USER=${{ secrets.DEV_SSH_USER }}" >> $GITHUB_ENV
            echo "::set-output name=ssh_key::DEV_SSH_PRIVATE_KEY"
          fi

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'false'
          fetch-depth: 0

      - name: Set up SSH for DEV environment
        if: env.ENVIRONMENT == 'dev'
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}

      - name: Set up SSH for STAGING environment
        if: env.ENVIRONMENT == 'staging'
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}

      - name: Install SSH dependencies
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo "SSH setup completed"

      - name: Debug connection
        run: |
          echo "Attempting to connect to ${{ env.SERVER_HOST }} as ${{ env.SSH_USER }}"
          ssh -v ${{ env.SSH_USER }}@${{ env.SERVER_HOST }} "echo Connection successful"

      - name: Deploy to Server
        run: |
          echo "Deploying to ${{ env.ENVIRONMENT }} environment on ${{ env.SERVER_HOST }}"
          TARGET_BRANCH="${{ github.base_ref || github.ref_name }}"
          ssh -v ${{ env.SSH_USER }}@${{ env.SERVER_HOST }} "cd ~/quantus-alpha && git checkout ${TARGET_BRANCH} && git pull origin ${TARGET_BRANCH} && ./scripts/service-deploy.sh ${{ env.ENVIRONMENT }} ${{ env.CLEAN_CACHE }}"
